### ISSUE TITLE
Kaniko should allow to pass a certificate for a self-signed registry

### ISSUE THREAD

**Issue by antechrestos** [GoogleContainerTools/kaniko#1100]
Just like options `--skip-tls-verify-registry`,  or `--skip-tls-verify`, kaniko should allow user to pass a certificate for a given registry

This could be something like `--registry-certificate my.registry.url=/path/to/the/certificate.cert`

**Comment by nishit93-hub** [comment]
@antechrestos Hi using the Kaniko argument as


```
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
        - "--context=dir:///application-dockerfile"
        - "--destination=jfrog.local.com/springboot/maven:5.0"
        - "--registry-certificate jfrog.local.com=/kaniko/.docker/certs/ca-certificates.crt"
```
But it is giving me an  error 
`Unknown flag --registry-certificate jfrog.local.com`

**Comment by MrMYHuang** [comment]
> @antechrestos Hi using the Kaniko argument as
> 
> ```
>     container:
>       image: gcr.io/kaniko-project/executor:latest
>       command: [/kaniko/executor]
>       args:
>         - "--context=dir:///application-dockerfile"
>         - "--destination=jfrog.local.com/springboot/maven:5.0"
>         - "--registry-certificate jfrog.local.com=/kaniko/.docker/certs/ca-certificates.crt"
> ```
> 
> But it is giving me an error `Unknown flag --registry-certificate jfrog.local.com`

Try this:
```
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
        - "--context=dir:///application-dockerfile"
        - "--destination=jfrog.local.com/springboot/maven:5.0"
        - "--registry-certificate"
        - "jfrog.local.com=/kaniko/.docker/certs/ca-certificates.crt"
```
