### ISSUE TITLE
Question, dynamically create ECR repository if not exists

### ISSUE THREAD

**Issue by valdestron** [GoogleContainerTools/kaniko#1120]
I am using Jx and Kaniko executor in the pipeline. I need dynamically create repository in the ECR if it does not exists, how can i do that, my jenkins-x.yaml. The issuei s not related to jenkinsx, I am wondering if I can just somehow tell executor to use instance role permissions and create the repository dynamically.

```yaml
pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        agent:
          image: gcr.io/kaniko-project/executor
        stages:
          - name: build-and-push
            options:
                volumes:
                  - name: docker-config
                    secret:
                      secretName: jenkins-docker-cfg
                containerOptions:
                  volumeMounts:
                    - name: docker-config
                      mountPath: /kaniko/.docker/
            parallel:
              - name: batch-2
                steps:
                - name: container-build
                  command: /kaniko/executor
                  args:
                    - --dockerfile=/workspace/source/microservices/microservice1/Dockerfile
                    - --destination=xxxx.dkr.ecr.xxx.amazonaws.com/repo/microservices/microservice1:${inputs.params.version}
                    - --context=/workspace/source
```

Getting error:
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "XXX.dkr.ecr.xxxx.amazonaws.com/repo/microservices/microservice1:0.0.0-SNAPSHOT-PR-5-56": NAME_UNKNOWN: The repository with name 'repo/microservices/microservice1' does not exist in the registry with id 'XXXX'

```
