### ISSUE TITLE
Missing multistage dependencies

### ISSUE THREAD

**Issue by pcoves** [GoogleContainerTools/kaniko#1206]
**Actual behavior**

The built image using `kaniko` is missing dependencies while it works just fine with `docker`

**Expected behavior**

The built image must ship my software dependencies

**To Reproduce**

1. clone https://gitlab.com/pcoves/pcoves.gitlab.io
2. `docker run --rm -v $(pwd):/workspace -w /workspace registry.gitlab.com/pcoves/pcoves.gitlab.io:latest build` (This works)
3. `docker run --rm -v $(pwd):/workspace -w /workspace registry.gitlab.com/pcoves/pcoves.gitlab.io:kaniko build` (This fails)

**Additional Information**
 - Dockerfile 
```
FROM haskell:latest as build

COPY . /pcoves.gitlab.io
WORKDIR /pcoves.gitlab.io
RUN stack install

FROM gcr.io/distroless/base

COPY --from=build /root/.local/bin /root/.local/bin
COPY --from=build /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
COPY --from=build /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/x86_64-linux-gnu/libgmp.so.10

ENTRYPOINT ["/root/.local/bin/pcoves-gitlab-io"]
```

 - Build Context
```yml
master:
  stage: master
  image: docker:latest
  dependencies:
    - dev
  cache:
    paths:
      - _cache
      - .stack-work
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/pcoves/pcoves.gitlab.io .
    - docker push registry.gitlab.com/pcoves/pcoves.gitlab.io
  only:
    - master

kaniko:
  stage: kaniko
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:kaniko
  only:
    - kaniko
```

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|
