### ISSUE TITLE
Kaniko Container can't exectute sh command

### ISSUE THREAD

**Issue by montezuma93** [GoogleContainerTools/kaniko#1212]
Hey,

we want Jenkins to start a pod with two containers, JNLP and Kaniko, for creating images, but when running our Kaniko Container as root, the "sh" command can't be executed in our pipeline won't continue to run.

In this issue: https://github.com/GoogleContainerTools/kaniko/issues/653, someone seems to have a similiar problem. But sadly we saw that this issue was closed without telling how it was solved.
Now we have the pretty similiar problem.

The JNLP container is defined in our Jenkins.
This is our yml definition of the pod and kaniko container:

```
kind: "Pod"
spec:
  restartPolicy: Never
  containers:
    - name: kaniko
      image: 'internal-registry/gcr.io/kaniko-project/executor:debug-v0.19.0'
      imagePullPolicy: 'Always'
      command:
        - /busybox/cat
      tty: true
      workingDir: /home/jenkins/agent
      env:
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
          readOnly: false
        - name: kaniko-docker-volume
          mountPath: /kaniko/.docker
        - name: ca-certificates-volume
          mountPath: /kaniko/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
        - name: system-tmp-volume
          mountPath: /tmp
          readOnly: false
      securityContext:
        readOnlyRootFilesystem: false
        runAsUser: 0
  volumes:
    - name: workspace-volume
      emptyDir:
        medium: "Memory"
    - name: kaniko-docker-volume
      emptyDir:
        medium: "Memory"
    - name: ca-certificates-volume
      configMap:
        name: ca-certificates
        items:
          - key: cert.pem
            path: ca-certificates.crt
    - name: system-var-volume
      emptyDir:
        medium: "Memory"
    - name: system-tmp-volume
      emptyDir:
        medium: "Memory"
```

This is what we want to do with our pipeline:

```
podTemplate(yaml: yaml, showRawYaml: true) {
    node(POD_LABEL) {
            // --- JNLP ---
            stage('Checkout') {
                container(name: 'jnlp') {
                    workspacePath = sh(script: 'echo `pwd`', returnStdout: true).trim()
                    writeFile file: "Dockerfile", text: """
                        FROM debian/stretch:1.0-Final.0
                        CMD ["/bin/bash"]
                    """
                }
                containerLog(name: 'jnlp')
            }

            // --- KANIKO ---
            stage('build') {
                try {
                    container(name: 'kaniko', shell: '/busybox/sh') {
                        withEnv(['PATH+EXTRA=/busybox:/kaniko']) {
                            echo sh(script: "id", returnStdout: true).trim()
                        }
                        withCredentials([[$class: 'VaultUsernamePasswordCredentialBinding',
                               credentialsId: 'vault', usernameVariable: 'USERNAME',      
                               passwordVariable: 'PASSWORD']]) {
                                   writeFile file: "config.json", text: """{ "auths": { 
                                   "https://internal-registry": { "username": "$USERNAME", 
                                   "password": "$PASSWORD" } } }"""
                               }
                 sh 'mv `pwd`/config.json /kaniko/.docker/config.json'
                 sh '/kaniko/executor --verbosity debug 
                      --dockerfile `pwd`/Dockerfile --context dir://`pwd`  
                      --insecure --skip-tls-verify
                      --destination gcr.io/kaniko-project/executor:debug--swp'
                } finally {
                    containerLog(name: 'jnlp')
                    containerLog(name: 'kaniko')
                }
            }
        }
    }
```

We want Kaniko to read the Dockerfile (which will later be not written in this part of the code) and build an image and push it to our internal registry.
We already decided, that we need to run Kaniko as root user as it wants to copy the Dockerfile directly at the start of the script to the path /kaniko/Dockerfile and the container needs permissions to do so.

But when we use: runAsUser: 0, the container can't run the sh command and nothing happens. Why can't the sh command be executed when running kaniko as root?

Both container are up and running and the only thing our log is showing to us is:
```
2020-04-28T18:35:54.461  [Pipeline] stage
2020-04-28T18:35:54.464  [Pipeline] { (build)
2020-04-28T18:35:54.515  [Pipeline] container
2020-04-28T18:35:54.517  [Pipeline] {
2020-04-28T18:35:54.570  [Pipeline] withEnv
2020-04-28T18:35:54.571  [Pipeline] {
2020-04-28T18:35:54.618  [Pipeline] sh
```

Best regards. 
Any help is appreciated.

**Comment by sbeaulie** [comment]
I get a similar behavior with this simple pipeline in GKE. Took the latest debug tag `debug-v0.19.0` and a dummy dockerfile from git. Removed any registry.

```
podTemplate(yaml: """
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.19.0
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
"""
  ) {

  node(POD_LABEL) {
    stage('Build with Kaniko') {
      git 'https://github.com/CWempe/docker-dummy.git'
      container('kaniko') {
        sh '/kaniko/executor -f `pwd`/Dockerfile -c `pwd` --destination=image --tarPath=`pwd`'
      }
    }
  }
}
```

All I see is it hanging. If I `kubectl exec -it <container> -c kaniko sh` in the running container I can run `/kaniko/executor` but it just hangs. I tried `/kaniko/executor --help` but I don't know if that's supported. Is there any smaller test I can run?

**Comment by montezuma93** [comment]
We use Jenkins and the Kubernetes Plugin. After trying out a lot, we found out that both containers, the JNLP container (which is used for Communication with Jenkins Master) and the Kaniko Container both need to be run as root. We also add one more container (Hadolint) which also needs to be run as root. So solution is to use root for all container:
```
 securityContext:
        runAsUser: 0
```
No idea how to run Kaniko as a container in Kubernetes without giving every container in the pod root rights.

@sbeaulie how is your Pod security and the security for the JNLP container defined? Try to use securityContext: runAsUser: 0 for everything, but this should be the overall goal...

**Comment by sbeaulie** [comment]
Thank for trying these out and trying to help me.

Base on the kubernetes docs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#securitycontext-v1-core it seems like the securityContext can be set at the container level or the pod level.

I changed my pod definition at the pod level, and it seems to apply the root user for both containers 'jnlp' and 'kaniko'

**Before the 'fix'**
Without the runAsUser: 0 the kaniko container runs as root, but jnlp runs as 'jenkins' here is how I checked:
```
$ kubectl exec -it legacy-pipeline-docker-build-26-sjnxr-31z9m-mdh14 -c jnlp sh

(in container):
$ ps -ef | grep java
jenkins        1       0 16 16:24 ?        00:00:21 /usr/local/openjdk-8/bin/java -cp /usr/share/jenkins/agent.jar hudson.remoting.jnlp.Main -headless -url https://cinext-jenkinsmaster-sre-prod-1.delivery.puppetlabs.net/ -workDir /home/jenkins/agent 0715eb020cf8d2785dc800f29799ef59a3c21e6afa318a0471991c5cb3eb98fc legacy-pipeline-docker-build-26-sjnxr-31z9m-mdh14
jenkins      185     179  0 16:26 pts/0    00:00:00 grep java
```
and kaniko was already running root, note the `ps -ef` for busybox shell shows PID, USER
```
PID   USER     TIME  COMMAND
    1 0         0:00 /busybox/cat
    6 0         0:00 sh
   19 0         0:00 sh -c ({ while [ -d '/home/jenkins/agent/workspace/legacy_pipeline_docker_build@tmp/durable-3b5f3383' -a \! -f '/home/jenkins/agent/workspace/legacy_pipeline_docker_build@tmp/durable-3b5f3383/jen
   20 0         0:00 sh -c ({ while [ -d '/home/jenkins/agent/workspace/legacy_pipeline_docker_build@tmp/durable-3b5f3383' -a \! -f '/home/jenkins/agent/workspace/legacy_pipeline_docker_build@tmp/durable-3b5f3383/jen
   21 0         0:00 sh -xe /home/jenkins/agent/workspace/legacy_pipeline_docker_build@tmp/durable-3b5f3383/script.sh
   27 0         0:00 /kaniko/executor --verbosity debug --dockerfile /home/jenkins/agent/workspace/legacy_pipeline_docker_build/Dockerfile --context /home/jenkins/agent/workspace/legacy_pipeline_docker_build --destin
   44 0         0:00 sleep 3
   45 0         0:00 ps -ef
```

**After the 'fix'**
With the fix you suggested, I see the jnlp container using root, but the kaniko executor still does not output anything!
With the security context set at the pod level via:
```
podTemplate(yaml: """
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.19.0
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: artifactorydockercreds
          items:
            - key: .dockerconfigjson
              path: config.json
  securityContext:
    runAsUser: 0
"""
  ) {

  node(POD_LABEL) {
    stage('Build with Kaniko') {
      git 'https://github.com/CWempe/docker-dummy.git'
      container('kaniko') {
        sh '/kaniko/executor --verbosity debug --dockerfile `pwd`/Dockerfile --context `pwd` --destination=image --tarPath=`pwd`'
      }
    }
  }
}
```


I double checked again that the process is running as root with `ps -ef`


```
# ps -ef | grep java
root           1       0 15 16:33 ?        00:00:20 /usr/local/openjdk-8/bin/java -cp /usr/share/jenkins/agent.jar hudson.remoting.jnlp.Main -headless -url https://cinext-jenkinsmaster-sre-prod-1.delivery.puppetlabs.net/ -workDir /home/jenkins/agent c1273263985210367787215d8c002dfc18f54f62a673784795538b3512ea894b legacy-pipeline-docker-build-27-0pxbn-2l193-bcwbv
root         172     166  0 16:35 pts/0    00:00:00 grep java
```

Conclusion: I can run the jnlp container and kaniko container as root via the security context set at the pod level, but there is still nothing output by the kaniko command.

I also tried the `shareProcessNamespace: true` to no avail...

**Comment by montezuma93** [comment]
Keep in mind that Kaniko doesn't have the shell "bin/sh", instead you need to use the "busybox/sh" shell. 
You can define the shell a specific container should use like this:
```
container(name: 'kaniko', shell: '/busybox/sh'){
    sh '/kaniko/executor ....
}
```

Maybe that helps?

**Comment by sbeaulie** [comment]
Thanks for trying to help. I tried the above it didnt make a difference. Also even without it Icould see the process in the process space by going into the container and running `ps -ef` 

I looks like my issue is like https://github.com/GoogleContainerTools/kaniko/issues/937 but that was closed without any workaround or solution.

I tried killing the process and got a similar output
```
SIGABRT: abort
PC=0x465b01 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x2c428c8, 0x80, 0x0, 0x0, 0x0, 0x7fff00000000, 0x439b93, 0xc0004072c8, 0x7fff1817b668, 0x40acaf, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:567 +0x21
runtime.futexsleep(0x2c428c8, 0x7fff00000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:44 +0x46
runtime.notesleep(0x2c428c8)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9f
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:1971 +0x88
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2454 +0x4a6
runtime.park_m(0xc000000180)
	/usr/local/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [sleep, locked to thread]:
time.Sleep(0xdf8475800)
	/usr/local/go/src/runtime/time.go:198 +0xba
k8s.io/kubernetes/pkg/credentialprovider/gcp.runWithBackoff(0xc0003a3d10, 0x0, 0x2c42780, 0x7f4b1e6c07d0)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go:186 +0x32
k8s.io/kubernetes/pkg/credentialprovider/gcp.(*containerRegistryProvider).Enabled(0xc00011a5a0, 0xc00036bc20)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go:209 +0x7c
k8s.io/kubernetes/pkg/credentialprovider.NewDockerKeyring(0x2, 0xb)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go:55 +0x123
github.com/google/go-containerregistry/pkg/authn/k8schain.init()
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/k8schain.go:42 +0x22

goroutine 33 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2c417c0)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/golang/glog/glog.go:410 +0x26f
```

**Comment by sbeaulie** [comment]
In case people wonder, `kaniko/executor` will hang forever if it cannot reach `metadata.google.internal` in GKE.

kaniko code https://github.com/GoogleContainerTools/kaniko/blob/v0.19.0/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go#L194-L204

it would have saved a lot of headache if it had at least outputted a warning/info/debug error.

**Comment by tejal29** [comment]
@sbeaulie The code you are pointing too is from the vendor dir. I am not sure what `withCredentials` does here. Is there a way you can provide us the generated `pod.yaml`.

Its not pretty to see a runtime stacktrace. We will look into this.

**Comment by sbeaulie** [comment]
Seems to happen if `metadata.google.internal` does not resolve. It'd be better to get something logged at the debug/info or warning level to say it couldn't be reached.

**Comment by sbeaulie** [comment]
@tejal29 this can be reproduced with:

**Reproduction steps**

```
apiVersion: v1
metadata:
  name: kaniko
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.19.0
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
  securityContext:
    runAsUser: 0
```

1. connect to the running container with `kubectl exec -it kaniko -- sh` 
2. make sure `metadata.google.internal` does not resolve, for example setting it to 127.0.0.1 in `/etc/hosts` should do it
3. run `/kaniko/executor --help`

the app will hang without any useful output.
