### ISSUE TITLE
Missing '.docker' folder in release 0.20.0 break backward compatibility in some pipelines

### ISSUE THREAD

**Issue by arum31** [GoogleContainerTools/kaniko#1227]
**Actual behavior**
My CI/CD (gitlab) image build job looks like this:

```yaml
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.20.0
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"gitlab-ci-token\",\"password\":\"${API_KEY}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/docker/Dockerfile --destination ${IMAGE_NAME}
```

This raises an error during the config file creation:
```shell
 echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"_\",\"password\":\"${API_KEY}\"}}}" > /kaniko/.docker/config.json
/busybox/sh: eval: line 91: can't create /kaniko/.docker/config.json: nonexistent directory
```

After entering the image there is no `/kaniko/.docker` folder as expected (as of v0.19.0).

Tested with:
gcr.io/kaniko-project/executor:debug-v0.19.0
gcr.io/kaniko-project/executor:debug-v0.20.0

**Expected behavior**
`/kaniko/.docker` folder exists.

**To reproduce**

1. `docker run -it --rm --entrypoint="" gcr.io/kaniko-project/executor:debug-v0.19.0 sh`
2. `ls -ail /kaniko`
3. A folder `.docker` should exist
4. Run into v0.20.0: `docker run -it --rm --entrypoint="" gcr.io/kaniko-project/executor:debug-v0.20.0 sh`
5. After a `ls -ail /kaniko` you should note there is no more `.docker` folder
