### ISSUE TITLE
Multistage with debug and cri-o deletes /busybox directory

### ISSUE THREAD

**Issue by alxbse** [GoogleContainerTools/kaniko#1275]
**Actual behavior**

When doing multistage builds in cri-o the /busybox directory gets deleted.

**Expected behavior**

When doing multistage builds in cri-o the /busybox directory should remain and commands in it should still run.

**To Reproduce**
1. Have access to a kubernetes cluster using cri-o as container runtime.
2. Create this simple pod to test behaviour.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerfile
data:
  Dockerfile: |
    FROM alpine as greeter
    RUN touch /hello
    FROM scratch
    COPY --from=greeter /hello /hello
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - command:
    - /busybox/cat
    tty: true
    image: gcr.io/kaniko-project/executor:debug-v0.22.0
    name: kaniko
    volumeMounts:
      - name: hello
        mountPath: /test
    workingDir: /test
  volumes:
    - name: hello
      configMap:
        name: dockerfile
```
3. Execute a command in the container `kubectl exec -it kaniko -- ls`. It works
4. Do the kaniko build `kubectl exec -it kaniko -- /kaniko/executor --no-push`. It works.
5. Try the same ls command `kubectl exec -it kaniko -- ls`. It gives an "executable file not found in $PATH" error.

**Additional Information**
Using `gcr.io/kaniko-project/executor:debug-v0.22.0` in a kubernetes 1.18.0 cluster with cri-o 1.18.0 as the container runtime.

Looking into the differences between docker/containerd and cri-o it seems that the cause for this issue is that cri-o handles volumes in images a bit differently. Unlike containerd cri-o will just create a directory for the volume in the container filesystem and in the case of the of the kaniko debug container, since the `busybox` directory already exists cri-o will do nothing with it.

Comparing the logs with trace verbosity, not included here because the are so large, does show that `/busybox` is never whitelisted when running in cri-o.

Using the `mountpoint` command in the debug container on the `/busybox` directory running with containerd outputs "/busybox is a mountpoint" 
Runing the same command with cri-o outputs "/busybox is not a mountpoint".

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
