### ISSUE TITLE
Loading built image to local docker daemon while pushing the image to destination parallelly

### ISSUE THREAD

**Issue by Matts966** [GoogleContainerTools/kaniko#1331]
**Feature Description**
When using kaniko on cloud build, it is desireble to load built image to local docker daemon while pushing the image to destination parallelly.

For example, destination specification like below can suggest kaniko to load image to local docker daemon.

```bash
/kaniko/executer --destination /var/run/docker.sock
```

If this feature is acceptable but not high priority, can I try make a PR, because we would like to fasten our cloud build steps?

Or can we already take another work around?

**Additional Information**
 - cloudbuild.yaml

```yaml
steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --cache=true
# Pulling image takes long time...(tarPath and docker load also takes long time)
- name: gcr.io/$PROJECT_ID/image
   args: [ run ]
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
