### ISSUE TITLE
Kaniko builds fail on k8s GitLab CI runner when /etc/ssh is mounted

### ISSUE THREAD

**Issue by JacobHenner** [GoogleContainerTools/kaniko#1353]
**Actual behavior**
When kaniko is used to build an image within a GitLab CI Kubernetes [executor](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html), the build fails with the following error if `/etc/ssh` is mounted within the executor (the Kubernetes pod created by GitLab for the build).

```
[37mDEBU[0m[0049] Not adding /etc/ssh because it is ignored    
[37mDEBU[0m[0049] Whiting out /etc/ssh/.wh..wh..opq            
error building image: error building stage: failed to get filesystem from image: removing whiteout etc/ssh/.wh..wh..opq: unlinkat /etc/ssh/.wh..opq: read-only file system
```

However, if I change the mount path to something else (e.g. `/etc/ssh.bak/`), this error does not occur.

I wonder if this is due to the presence of /etc/ssh within the FROM image itself. Perhaps if `/etc/ssh.bak` existed in the image, it'd fail too? I'm not sure why the mounts on the system where kaniko is executing would interact with the paths in the container image.

**Expected behavior**
I expected the kaniko build to work successfully, without being affected by the mounts within the Kubernetes pod where kaniko is running.

**To Reproduce**
1. Run kaniko within a GitLab CI Kubernetes executor pod, with the GitLab runner configured to mount the contents of a ConfigMap as `/etc/ssh`
2. Wait for kaniko to fail with the above error.

**Additional Information**
 - Dockerfile 

```
FROM <internal image>

RUN ls -la

CMD bash
```
 
- Build Context - No additional build context
 - Kaniko Image (fully qualified with digest) - `gcr.io/kaniko-project/executor@sha256:d60705cb55460f32cee586570d7b14a0e8a5f23030a0532230aaf707ad05cecd`
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by JacobHenner** [comment]
I just tested using a FROM image without `/etc/ssh`, which leads me to believe that somehow there is a conflict when a path exists within both the image and the kaniko host, if the path on the kaniko host is read-only (as it would be for a read only Kubernetes ConfigMap volume)?

**Comment by tejal29** [comment]
@JacobHenner Can you please specify your mount definition in the pod spec and the debug logs?

**Comment by tejal29** [comment]
Looks like, kaniko is missing the fact that `/etc/ssh` is mounted.

**Comment by JacobHenner** [comment]
```
yaml
    volumeMounts:
    - mountPath: /builds
      name: repo
    - mountPath: /volume/obscuredA
      name: obscuredA
    - mountPath: /volume/obscuredB
      name: obscuredB
    - mountPath: /volume/obscuredC
      name: obscuredC
    - mountPath: /etc/ssh
      name: ssh
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-vnb9h
      readOnly: true
```

```yaml
  volumes:
  - configMap:
      defaultMode: 420
      name: ssh
    name: ssh
```
