### ISSUE TITLE
Error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile

### ISSUE THREAD

**Issue by Morride** [GoogleContainerTools/kaniko#1414]
**Actual behavior**
I found this problem while checking the error message.
```
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
      --registry-mirror string                    Registry mirror to use has pull-through cache instead of docker.io.
  -v, --verbosity string                          Log level (trace, debug, info, warn, error, fatal, panic) (default "info")
```
This is my pod yaml.
```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/Dockerfile",
           "--context=dir://workspace",
           "--destination=harbor.vkdata.com/library/test-kaniko"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-pvc
```
And I created workspace.

kaniko-secret
```
kubectl -n anonymous create secret generic kaniko-secret --from-file=/kaniko/.docker/config.json
```
config.json
```
{
        "auths": {
                "harbor.data.com": {
                        "auth": "xxxxxxxxxxx"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.09.6 (linux)"
        }
}
```
dockerfile-pv and dockerfile-pvc
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: dockerfile-storage
  hostPath:
    path: /kaniko/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dockerfile-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: dockerfile-storage
```
I looked at other similar issues but they couldn’t solve it.
**Expected behavior**
I hope kaniko runs normally.
**To Reproduce**
1. kubectl create -f pod.yaml
2. kubectl  logs  kaniko --all-containers |grep error

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
```
FROM nginx
ENTRYPOINT ["/bin/bash", "-c", "echo hello"]
```
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
nothing
 
- Kaniko Image (fully qualified with digest)
 gcr.io/kaniko-project/executor:latest              50388657b978
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [No] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [Yes] </li></ul>|
