### ISSUE TITLE
/busybox/sh: eval: line 136: -: not found

### ISSUE THREAD

**Issue by MrAmbiG** [GoogleContainerTools/kaniko#1418]
**Actual behavior**
`.gitlab-ci.yml` file is provided below. I believe kaniko with debug tag has shell in it but it somehow complains that shell isn't present or found. The gitlab-runner or the whole setup is run in privileged or root mode. So access should not be a problem.
similar issue here --> https://github.com/GoogleContainerTools/kaniko/issues/758

**Expected behavior**
It should build and push image to my on prem registry.

**To Reproduce**
```
stages:
  - kaniko # to run on kaniko branch
kaniko:
  only:
    refs: # branches to run on
      - kaniko
  stage: kaniko
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - test -d "$KANIKO_DIR" && echo "$KANIKO_DIR Exists" || mkdir -p "$KANIKO_DIR"
    - echo "{\"auths\":{\"$MYMY_REGISTRY\":{\"username\":\"$MYMY_REGISTRY_USER\",\"password\":\"$MYMY_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      echo "-----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----" >> /kaniko/ssl/certs/additional-ca-cert-bundle.crt
      - echo 'end of before script'
  script:
    - test -d "$KANIKO_DIR" && echo "$KANIKO_DIR Exists" || mkdir -p "$KANIKO_DIR"
    - echo "{\"auths\":{\"$MYMY_REGISTRY\":{\"username\":\"$MYMY_REGISTRY_USER\",\"password\":\"$MYMY_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $MYMY_PROJECT_DIR --dockerfile $MYMY_PROJECT_DIR/Dockerfile --destination $MYMY_REGISTRY_IMAGE
variables:
  ROCM_REGISTRY_IMAGE: 'MYIMAGENAME_WITH_URL'
  ROCM_PROJECT_DIR: .
  KANIKO_DIR: "/kaniko/.docker"
```

**Additional Information**
Gitlab runner 13.3.x
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
