### ISSUE TITLE
Can't install to container, before doing a build in GitLab. (Missing package manager?)

### ISSUE THREAD

**Issue by Cameronsplaze** [GoogleContainerTools/kaniko#1440]
**Actual behavior**
For running in GitLab, I have a yml similar to:
```yaml
image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: [ docker ]
  stage: Deploy-staging
  script:
    # --- Login stuff here --- #
   # --- Setup more here? Like opkg install git? --- #
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${REPO_URL}
```
That part works great, but I can't find how to do any setup before building the image. There's a couple repo's I'd like to git clone before getting to the build part, so everything's together. I can't find how to install git, or any other packages I might need in the future. Is there a package manager I'm just missing? It's busybox, so I tried opkg, but it says it's not found. I also tried apt, pacman, yum, etc without any luck. 

**Expected behavior**
A package manager to install missing libraries to container, before building containers in a GitLab runner.

**Additional Information**
 - Dockerfile 
   N/A
 - Build Context
   N/A
 - Kaniko Image (fully qualified with digest)
   gcr.io/kaniko-project/executor:debug

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ X ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by cjshowalter** [comment]
I think I got around this, by having another GitLab job (Ubuntu) download git, clone the repo, and upload an artifact with the files to the Kaniko job. Is this the intended way to add files for Kaniko to build with in GitLab? It seems slightly overkill just to add files to me, but I'm new to CI-CD. Maybe keeping jobs super small in gitlab is intended? Any way, thanks in advance for any advice you might have on this! I was stuck on it for a while now lol.
I stripped this down, so it might not be 100% accurate, but my solution was something like this:
```yaml
Staging setup:
  image: ubuntu:18.04
  stage: Build-staging
  script:
    - apt update && apt install -y git
    - git clone <mylib.git repo>
  artifacts:
    name: "Lib-$CI_JOB_ID"
    paths:
      - mylib/
    exclude:
      - mylib/.git/**/*
    expire_in: 1 day

image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: [ docker ]
  stage: Deploy-staging
  dependencies:
    - "Staging setup"
  script:
    # --- Login stuff here --- #
    # --- artifact is added to project by default, setup already done!! ---
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${REPO_URL}
```
