### ISSUE TITLE
Feature Request - Extracting build artifacts

### ISSUE THREAD

**Issue by rcollette** [GoogleContainerTools/kaniko#1450]
Prior to using Kaniko, I was doing builds on a Gitlab Shell Executor on a dedicated VM.   In that mode I was able to extract build artifacts from a "build and test" target prior to generating the final "application" target.

```
docker build \
  -t ${DOCKER_TAG_NAME}:${VERSION} \
  -t ${DOCKER_TAG_NAME}:latest \
  --build-arg VERSION=${VERSION} \
  --target build-and-test \
  --file buildTestPublish.Dockerfile .
# To copy files we must create a container.  We cannot copy from an image.  The container doesn't start though.
echo "Creating container ${DOCKER_TAG_NAME}:${VERSION} for file copying."
id=$(docker create ${DOCKER_TAG_NAME}:${VERSION})
echo "Copying unit-tests out of container to /unit-tests"
#Docker cp source paths must be from the root.
rm -rf unit-tests | exit 0
mkdir unit-tests
docker cp ${id}:/app_build/The.Solution.Name/The.Solution.Name.HttpClient.Test/unit-tests/junit.xml unit-tests/junit-HttpClient.xml
docker cp ${id}:/app_build/The.Solution.Name/The.Solution.Name.Repository.Test/unit-tests/junit.xml unit-tests/junit-Repository.xml
docker cp ${id}:/app_build/The.Solution.Name/The.Solution.Name.Service.Test/unit-tests/junit.xml unit-tests/junit-Service.xml
docker cp ${id}:/app_build/The.Solution.Name/The.Solution.Name.Web.Test/unit-tests/junit.xml unit-tests/junit-Web.xml
echo "Removing container ${DOCKER_TAG_NAME}:${VERSION}."
docker rm -v ${id}
```

Now that I am building on OpenShift with Kaniko I don't seem to have a way to get artifacts out of the built image.  I can't mount a volume to the kaniko image because Gitlab doesn't support running an image with parameters.   I have to run the debug image and script the executor like:

```
build:
  stage: build
  <<: *runners
  <<: *except_master_and_prodfix
  variables:
    #Provides the base registry path to which /cache will be appended.
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "sh" ]
  artifacts:
    paths:
      - artifacts/
  script:
    # We cannot git merge from master here because busybox used in Kaniko does not have git nor does it have
    # a package installer.
    # Docker command is not available in Kaniko image so we have to create the .docker/config.json file manually.
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - mkdir -p artifacts
    #This builds but does not push to the registry
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --no-push
      --skip-unused-stages=true
      --cache=true
      --cache-repo=${CI_REGISTRY_IMAGE}/cache
      --log-timestamp=true
      --log-format=text
      --target build-and-test
```

If there isn't currently a way to "mount" a file path into the executor  it would be helpful to be able to do so, such that generated artifacts can be copied to the mounted path (ex. /artifacts) and they would be written to the file system captured by Gitlab.

**Comment by ilionblaze** [comment]
I've run into this same issue, needing to extract the results of junit tests for reporting. This would be extremely useful.

**Comment by dpinchukov-ueni** [comment]
Same thing here. Currently I have to develop ugly hacks to build the project into a local tar file, then extracting artifacts to it, instead of simply telling kaniko to store artifacts in a directory that stays available after the build has finished.

**Comment by andrea-borraccetti** [comment]
You can find all the artifacts built inside the Dockerfile in /app folder of the kaniko container.
To reach your goal you can configure the CI in this way:

step:  
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$DOCKER_REPO\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination registry.local/image:latest --cache=true
    - cp -rf /app/* $CI_PROJECT_DIR/
  artifacts:
    when: always    
    reports:
      junit: ./**/target/**/TEST-*.xml

**Comment by rcollette** [comment]
@andrea-borraccetti - Thank you for the tip, but how did you even know about that directory?  Even with the debug image, there does not appear to be a way to run in interactive mode (no /bin/sh) and there is no `ls` command available so I can see what is in the app folder.

I'm flying blind at the moment.

**Comment by rcollette** [comment]
@andrea-borraccetti 

For some reason, when I run it in gitlab with the entry point as either "" or "sh", I get the error.
```
/busybox/sh: eval: line 144: cp: not found
$ cp -rf /build/reports $CI_PROJECT_DIR/public
Running after_script
00:00
time="2021-02-05T22:49:57Z" level=error msg="exec failed: container_linux.go:349: starting container process caused \"exec: \\\"sh\\\": executable file not found in $PATH\""
exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH"
```

I also tried invoking cp with an explicit path but no luck with that either.

```
$ /busybox/cp -rf /build/reports $CI_PROJECT_DIR/public
/busybox/sh: eval: line 144: /busybox/cp: not found
Running after_script
00:01
time="2021-02-05T23:00:09Z" level=error msg="exec failed: container_linux.go:349: starting container process caused \"exec: \\\"sh\\\": executable file not found in $PATH\""
exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH"
```

gitlab-ci.yml contains:
```yaml
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.3.0
    entrypoint: [""]
  script:
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --no-push
      --skip-unused-stages=true
      --cache=true
      --cache-repo=${CI_REGISTRY_IMAGE}/cache
      --log-timestamp=true
      --log-format=text
      --target build-and-test
      --verbosity=debug
      --build-arg NPM_TOKEN=${NPM_TOKEN}
    # Executor will create the WORKDIRs of the Dockerfile in its own container.
    - /busybox/cp -rf /build/reports $CI_PROJECT_DIR/public
```

**Comment by andrea-borraccetti** [comment]
I tried to execute **cp** and **ls** commands in my custom runner using the gitlab company instance and using gitlab.com with the standard runner and in each cases all works and i see the files outside the context with the configuration like this:
```

build:  
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY_IMAGE\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR--dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/image:latest --cache=true
    - ls /
```

In your case, it looks more like a problem of gitlab runner version or configuration

**Comment by rcollette** [comment]
Actually running an `ls` command before running kaniko executor works fine.  Running the 'ls` command after kaniko executor runs results in the error.  So I'm not entirely sure this is something related to my environment.

```yaml
variables:
  #CI_DEBUG_TRACE: "true"
  DOCKER_TAG_NAME: pdx-pdt
  DOCKER_IMAGE_VERSION: $CI_PIPELINE_ID.$CI_COMMIT_SHORT_SHA
  KANIKO_EXECUTOR_VERSION: debug-v1.3.0

stages:
  - build

# TEMPLATES
.runner_tags_template: &runners
  tags:
    - pdx
    - dind

.except_master_and_prodfix_template: &except_master_and_prodfix
  except:
    - /^prodfix\/.*$/
    - master
    - tags

# BUILD
build:
  stage: build
  <<: *runners
  <<: *except_master_and_prodfix
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_EXECUTOR_VERSION
    entrypoint: ["sh"]
  script:
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - ls
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --no-push
      --skip-unused-stages=true
      --cache=true
      --cache-repo=${CI_REGISTRY_IMAGE}/cache
      --log-timestamp=true
      --log-format=text
      --target build-and-test
      --verbosity=debug
      --build-arg NPM_TOKEN=${NPM_TOKEN}
    - ls

```

Build log with executor debug output is attached.
[GitlabBuildLog.txt](https://github.com/GoogleContainerTools/kaniko/files/5937454/GitlabBuildLog.txt)

**Comment by rcollette** [comment]
I can `cd` to the /busybox directory before running executor.   After running executor, if I try to `cd` to the directory, it says the director is not found.

```
time="2021-02-06T19:23:59Z" level=info msg="Skipping push to container registry due to --no-push flag"
$ cd /busybox
/busybox/sh: cd: line 158: can't cd to /busybox: No such file or directory
```

**Comment by rcollette** [comment]
@andrea-borraccetti 

I am able to duplicate this issue with a minimal Dockerfile.   It seems to be related to multi-stage builds.  If I target the base stage with executor, there are no issues.  If I target a second stage that relies on the first stage, the busybox directory is "gone" after the executor runs.

Dockerfile
```Dockerfile
#This target builds the API server and runs unit tests
FROM node:14.15-alpine3.12 AS base
LABEL type="build"

FROM base as build-and-test
LABEL type="build-and-test"
```

.gitlab-ci.yml
```yaml
variables:
  #CI_DEBUG_TRACE: "true"
  DOCKER_TAG_NAME: pdx-pdt
  DOCKER_IMAGE_VERSION: $CI_PIPELINE_ID.$CI_COMMIT_SHORT_SHA
  KANIKO_EXECUTOR_VERSION: debug-v1.3.0

stages:
  - build

# TEMPLATES
.runner_tags_template: &runners
  tags:
    - pdx
    - dind

.except_master_and_prodfix_template: &except_master_and_prodfix
  except:
    - /^prodfix\/.*$/
    - master
    - tags

# BUILD
build:
  stage: build
  <<: *runners
  <<: *except_master_and_prodfix
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_EXECUTOR_VERSION
    entrypoint: ["sh"]
  script:
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - pwd
    - cd /busybox
    - pwd
    - cd $CI_PROJECT_DIR
    - pwd
    - env
    - ls
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --no-push
      --target build-and-test
#cd /busybox fails when the target is something after the first stage of the Dockerfile
    - cd /busybox
    - pwd
    - ./env
    - ./ls
```

**Comment by SandhyaBanwarie** [comment]
Hello normally we use the source command to get the artifacts. How should we use/source the artifacts with kaniko build?

**Comment by alastairtree** [comment]
I had the same issue and developed a workaround:
- tell kaniko to ignore the path where my artifacts are saved to (MY-APP-ARTIFACT-*)
- use no-push and the local registry
- copy the artifacts from the root to the working directory (this is the only place gitlab will collect them from)

I could not get caching to work, but at least artifacts work now.

Example 

```yaml
build:
  stage: build
  image:
    name: "gcr.io/kaniko-project/executor:debug"
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR 
                       --dockerfile $CI_PROJECT_DIR/Dockerfile 
                       --destination registry.local/image:latest 
                       --no-push
                       --ignore-path /MY-APP-ARTIFACT-*
    - cp /MY-APP-ARTIFACT-**.tar.bz2 $CI_PROJECT_DIR

  artifacts:
    when: always 
    paths:
      - "MY-APP-ARTIFACT-*.tar.bz2"
```
