### ISSUE TITLE
missing files while caching is enabled

### ISSUE THREAD

**Issue by vivekthangathurai** [GoogleContainerTools/kaniko#1533]
**Actual behavior**

I am using a multi-stage (development, production) dockerfile and enabled caching. When the `development` target is built and layers are getting cached and when the copy of generated file in the production target from development fails.

**Expected behavior**
The generated file in the development target is not copied into the image of the production target.

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
```
FROM golang:1.15-buster as build

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn sqlite3

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs build-essential zip

WORKDIR /src

# Build Go server
ENV GO111MODULE on
ADD . .
RUN go mod download
# Build UI
# FLAGR_UI_POSSIBLE_ENTITY_TYPES is useful for limiting the choices of entity types
ARG FLAGR_UI_POSSIBLE_ENTITY_TYPES=null
ENV FLAGR_UI_POSSIBLE_ENTITY_TYPES ${FLAGR_UI_POSSIBLE_ENTITY_TYPES}
RUN cd ./browser/flagr-ui/ && yarn install && yarn run build
RUN make build

######################################
# Copy from build to alpine image
######################################
FROM debian:buster-slim as **production**
RUN apt-get update && apt-get install -y ca-certificates

ENV HOST=0.0.0.0
ENV PORT=18000
ENV FLAGR_DB_DBDRIVER=mysql
ENV FLAGR_RECORDER_ENABLED=false
ENV FLAGR_PROMETHEUS_ENABLED=true
ENV FLAGR_MIGRATION_FOLDER=./featureflag_files
ENV FLAGR_RBAC_FOLDER=./rbac_files

COPY --from=build   /src/rbac_files ./rbac_files
COPY --from=build   /src/appconfigr ./appconfigr
COPY --from=build   /src/browser/flagr-ui/dist ./browser/flagr-ui/dist
COPY --from=build   /src/dbmigration /dbmigration
COPY --from=build   /src/docs/api_docs/bundle.yaml ./bundle.yaml

RUN useradd --uid 1000 --gid 0 configr && \
    chown configr:root /src && \
    chmod g=u /src
USER 1000:0

EXPOSE 18000
COPY --from=build --chown=configr:root /src/featureflag_files ./featureflag_files
COPY --from=build --chown=configr:root /src/featureflag_files_incoming ./featureflag_files_incoming

CMD ["sh", "-c", "FLAGR_DB_DBCONNECTIONSTR=\"${DATABASE_USERNAME}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOSTNAME})/${DATABASE_NAME}?parseTime=true&interpolateParams=true\" ./appconfigr"]
```

 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)

  kaniko image is latest and target is production from the dockerfile. 
  `RUN make build` command generates the executable `appconfigr` in developement target
   ```
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--cache=true"
          - "--cache-repo={{workflow.parameters.docker_tag}}/build"
          - "--target=build"
          - "--destination={{workflow.parameters.docker_tag}}:dev-{{inputs.parameters.version}}"
   ```
  `COPY --from=build   /src/appconfigr ./appconfigr` command fails to execute says

```
     2020-12-23T06:32:05.965709978Z INFO[0119] COPY --from=build   /src/appconfigr ./appconfigr
    2020-12-23T06:32:05.965986675Z INFO[0119] Pushing layer ***.appdirect.***/appconfigr/appconfigr-test/build:1762aa7f75f5e8b57c2b55889eb45ff2f55aa45c83
    c7be71241fe4c112b45bd6 to cache now
    2020-12-23T06:32:05.966402775Z error building image: error building stage: failed to execute command: resolving src: failed to get fileinfo for /kaniko/0/
    src/appconfigr: lstat /kaniko/0/src/appconfigr: no such file or directory
```
   ```
    container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--cache=true"
          - "--cache-repo={{workflow.parameters.docker_tag}}/build"
          - "--target=production"
          - "--destination={{workflow.parameters.docker_tag}}:{{inputs.parameters.version}}"
          - "--destination={{workflow.parameters.docker_tag}}:latest"
          - "--cleanup"
  ```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
