### ISSUE TITLE
Kaniko "Hello world" on .gitlab.ci.yml fails

### ISSUE THREAD

**Issue by cslovell** [GoogleContainerTools/kaniko#1551]
I'm clearly doing something wrong here, but I can't figure it out...

**Actual behavior**
A simple hello world test of Kaniko fails. 

Dockerfile.dev:
```
FROM alpine
CMD ["echo", "Hello StackOverflow!"]
```

.gitlab-ci.yml: 
```
stages:
  - build
  - deploy

variables:
  DEV_IMAGE: dev-image-redacted
  BUCKET_NAME: bucket-redacted
  HOST_ARCH: linux/arm64
  PYTHON_IMAGE: python:3.8
  DOCKER_REGISTRY: container-registry-redacted
  CONTAINER_DEV_IMAGE: $DEV_IMAGE:$CI_COMMIT_SHORT_SHA
  TAG_CONTAINER_DEV_IMAGE: $DEV_IMAGE:$CI_COMMIT_REF_NAME
  LATEST_CONTAINER_DEV_IMAGE: $DEV_IMAGE:latest

docker_login: 
  stage: build
  image: $PYTHON_IMAGE
  before_script:
    - pip3 install awscli --upgrade
  script: 
    - DOCKER_AUTH_TOKEN=$(aws ecr get-login-password --region eu-central-1)
    - mkdir .docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"auth\":\"$DOCKER_AUTH_TOKEN\"}}}" > .docker/config.json
  artifacts: 
    paths: 
      - .docker/

build: 
  stage: deploy
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script: 
    - echo "uname -a"
    - echo $CI_PROJECT_DIR
    - mkdir -p /kaniko/.docker
    - cp .docker/config.json /kaniko/.docker/config.json
    - /kaniko/executor --customPlatform "$HOST_ARCH" --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.dev --destination $CONTAINER_DEV_IMAGE --destination $TAG_CONTAINER_DEV_IMAGE --destination $LATEST_CONTAINER_DEV_IMAGE
  dependencies: 
    - docker_login
```

Gitlab Runner config.toml: 
```
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Name Redacted"
  url = "url-redacted"
  token = "token-redacted"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:20.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```

output of $uname -a on gitlab runner machine: 
```
$uname -a
Linux ip-172-30-3-174 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:02:01 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

```
kaniko digest: sha256:473d6dfb011c69f32192e668d86a47c0235791e7e857c870ad70c5e86ec07e8c
```

**Expected behavior**
I expected it to build the container. 

**To Reproduce**
1. Setup a gitlab runner on AWS AMI ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20200907 using config.toml above.
2. Use the .gitlab-ci.yml above to build the hello world dockerfile above. 
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
