### ISSUE TITLE
Kaniko-Executor : Temporary files left after build in /kaniko folder

### ISSUE THREAD

**Issue by vinsoyo** [GoogleContainerTools/kaniko#1567]
**Actual behavior**
After building an image with kaniko-excecutor, some files are left on the file system in /kaniko folder like :
/kaniko/158726077
/kaniko/498146039

--cleanup option doesn't change that behavior.

**Expected behavior**
After build, these files are removed.

**Steps To Reproduce**

1) I have the following structure in a folder : 
**/myfolder/docker-compose.yml**
with content :
```
version: "3.9"
services:
  kaniko:
    image: gcr.io/kaniko-project/executor:debug
    command: --no-push --cleanup --context=/my-context
    volumes:
    - ./my-context:/my-context
    container_name: kaniko-issue
```
**/myfolder/my-context**
**/myfolder/my-context/Dockerfile**
with content
```
FROM node:10

Add folder-in-build-context .

ENTRYPOINT ["node"]
CMD ["index.js"]`

```
**/myfolder/my-context/folder-in-build-context**
**/myfolder/my-context/folder-in-build-context/file-in-build-context.txt**
with content : 
```
I am a file in build context
```

2) Run docker-compose up

3) After compose is completed and kaniko executor exited, execute 
`docker cp kaniko-issue/kaniko ./result` 

4) List files in folder result
