### ISSUE TITLE
--cache=ture did not take effect. Why?

### ISSUE THREAD

**Issue by renhao-0518** [GoogleContainerTools/kaniko#1570]
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.3.0 
    imagePullPolicy: IfNotPresent
    args: ["--dockerfile=Dockerfile",
           "--destination=harborsml.tsign.cn/common/kaniko:v1",
           "--context=workspace",
           "--cache=true",
           "--cache-dir=/cache",
           "-v=debug"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
      - name: kaniko-cache
        mountPath: /cache
      - name: dockerfile
        mountPath: /workspace/
  restartPolicy: Never
  volumes:
    - name: dockerfile
      hostPath:
        path: /root/
    - name: kaniko-secret
      secret:
        secretName: aliyun
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache
```
```
DEBU[0000] Copying file /workspace/Dockerfile to /kaniko/Dockerfile 
E0203 11:41:52.979343       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
DEBU[0006] Skip resolving path /kaniko/Dockerfile       
DEBU[0006] Resolved relative path workspace to /workspace/workspace 
DEBU[0006] Skip resolving path /cache                   
DEBU[0006] Skip resolving path                          
DEBU[0006] Skip resolving path                          
DEBU[0006] Skip resolving path                          
DEBU[0006] Built stage name to index map: map[]         
INFO[0006] Retrieving image manifest alpine:3.8         
INFO[0006] Retrieving image alpine:3.8                  
DEBU[0011] No file found for cache key sha256:954b378c375d852eb3c63ab88978f640b4348b01c1b3456a024a81536dafbbf4 stat /cache/sha256:954b378c375d852eb3c63ab88978f640b4348b01c1b3456a024a81536dafbbf4: no such file or directory 
```
