### ISSUE TITLE
Can't push images to gitlab registry when using group scoped token

### ISSUE THREAD

**Issue by rafagsiqueira** [GoogleContainerTools/kaniko#1577]
**Actual behavior**
After Kaniko builds the image, it fails to push it to the registry with the following error
error pushing image: failed to push to destination registry.un.org/ola/etips-api:: Post "https://registry.un.org/v2/ola/etips-api/blobs/uploads/": read tcp 10.208.49.75:52696->157.150.185.69:443: read: connection reset by peer

The connection reset by peer error is not very clear about what happened. Tried using project tokens, group tokens, user+password, hashes, for the kaniko/.docker/config.json, nothing seems to work.

**Expected behavior**
After building, kaniko should be able to push the image to the registry.

**To Reproduce**
Example .gitlab-ci.yml:
```yaml
stages:
  - build

docker:build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$GROUP_TOKEN_NAME\",\"password\":\"$GROUP_TOKEN_VALUE\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination registry.un.org/ola/etips-api:dev --image-name-with-digest-file image_tag
```

**Additional Information**
 - Kaniko Image: gcr.io/kaniko-project/executor:debug
 
 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
