### ISSUE TITLE
Error When Building Image with Kaniko

### ISSUE THREAD

**Issue by dogac00** [GoogleContainerTools/kaniko#1624]
**Actual behavior**
I am getting an error when building image with Kaniko in GitLab CI.

Our image build script is this:
```
.build:
    stage: Build 📦
    image:
      name: gcr.io/kaniko-project/executor
      entrypoint: [""]
    only:
      - master
    script:
      - echo "{\"auths\":{\"$REGISTRY_HOST\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASS\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_IMAGE
```

Our Dockerfile is this:
``` docker
FROM dotnet_runtime_image AS base
WORKDIR /app
EXPOSE 80

FROM dotnet_build_image AS build
WORKDIR /src
COPY /src/our_app_name.csproj src/
RUN dotnet restore "src/our_app_name.csproj"
COPY . .

RUN dotnet build "src/our_app_name.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "src/our_app_name.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "our_app_name.dll"]
```

**Expected behavior**
It shouldn't give any errors in `dotnet restore` phase because the `.csproj` file should be there with path `src/our_app_name.csproj`, I do not get any errors when building directly with `docker build`.

**To Reproduce**
1. Use given dockerfile and a dotnet project with the same name.
2. Use given GitLab CI script.

**Additional Information**
 - Dockerfile - Provided.
 - Build Context - GitLab CI.
 - Kaniko Image (fully qualified with digest) - `gcr.io/kaniko-project/executor:debug` with digest `sha256:e00dfdd4a44097867c8ef671e5a7f3e31d94bd09406dbdfba8a13a63fc6b8060`.
 
 **Triage Notes for the Maintainers**
 
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|
