### ISSUE TITLE
Reset ENTRYPOINT, run kaniko in CMD block

### ISSUE THREAD

**Issue by bittner** [GoogleContainerTools/kaniko#1651]
**Actual behavior**

Kaniko executor as `ENTRYPOINT` makes it hard to use the image for CI pipelines (e.g. [GitLab](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko)). You have to reconfigure the entrypoint to `/bin/sh` or reset its value using `ENTRYPOINT []`.

```yaml
# Example .gitlab-ci.yml (note the `entrypoint` below), taken from 
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
```

**Expected behavior**

The image should be usable with CI systems such as GitLab CI or GitHub Actions out-of-the-box (e.g. use an entrypoint script, fall back to `/bin/sh` when that is overridden, only use `CMD` to run kaniko for convenience or don't run kaniko by default at all).

A resulting CI setup would be simpler, e.g.

```yaml
build:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
  - ...
```

**To Reproduce**

1. Use the `debug` image with GitLab or GHA (e.g. `image: gcr.io/kaniko-project/executor:default`) without reconfiguring the `entrypoint`
2. Run the pipeline -- _it will fail_
3. Remove `ENTRYPOINT` and `CMD` (or set `ENTRYPOINT []`)
4. Run the pipeline -- _it will succeed_

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
