### ISSUE TITLE
Kaniko and Harbor

### ISSUE THREAD

**Issue by milica-nikolic** [GoogleContainerTools/kaniko#1732]
Hi there!

I am trying to find a way how can I with Kaniko's help build and push Docker image to Harbor from GitLab CI pipeline but I can't find any documentation on this.

Can someone please refer me to the documentation that explains how can I do this ?

I would really appreciate any help or advice on this topic because I already tried to follow docker-in-docker workflow with Docker executor from GitLab's documentation but I read that this is not recomended way to do this because I would need to disable all of the security mechanisms.

Kind regards,
Milica

**Comment by acouvreur** [comment]
We are using kaniko to build and deploy to harbor in our Jenkins pipelines.
Our Jenkins pipelines are provisioned with Kubernetes Pods, this is the Kaniko entry :
```yaml 
apiVersion: v1
kind: Pod
spec:
  containers:
   ...
   - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-registry-account
          mountPath: /kaniko/.docker
        - name: kaniko-cache
          mountPath: /cache

  volumes:
    - name: docker-registry-account
      projected:
        sources:
          - secret:
              name: docker-registry-account
              items:
                - key: .dockerconfigjson
                  path: config.json
    - name: kaniko-cache
      hostPath:
        path: /kaniko-cache
```

And we execute the following command in out kaniko container : 

```shell
/kaniko/executor -f ./docker/Dockerfile -c $(pwd) --cache=true --reproducible --label org.opencontainers.image.revision=GIT_SHA --label org.opencontainers.image.source=$GIT_URL --destination=registry.company.com/repository/image:version
```

Hope it helps you!
