### ISSUE TITLE
No information about push progress

### ISSUE THREAD

**Issue by eumel8** [GoogleContainerTools/kaniko#1747]
gitlab-runner 14.2.0
kaniko:debug

**Actual behavior**
We use kaniko in [Gitlab Runner](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html) to pull, build, and push a image
```yaml
image-build:
  tags:
    - k8s-executor
  stage: imagebuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - configdir=/kaniko/.docker
    - mkdir -p "$configdir"
    - echo "$DOCKER_CONFIG" | base64 -d > "$configdir/config.json"
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_REPOSITORY:$CI_COMMIT_SHA
      --cache=false
      --cache-copy-layers=false
      --cache-ttl=10s
      --cache-repo $CI_REGISTRY_IMAGE
      --push-retry 3
      --verbosity trace
      --log-timestamp
      --cleanup
```
. The source image is always the same. Push the image to a registry takes between seconds:
```bash
INFO[2021-09-20T21:40:45Z] Pushing image to mtr.external.otc.telekomcloud.com/eumel8/test:e280436ecd7a21f1919bcb44e00ed936561e80f4 
INFO[2021-09-20T21:40:46Z] Pushed image to 1 destinations  
```

and minutes:
```bash
INFO[2021-09-21T02:00:41Z] Pushing image to mtr.external.otc.telekomcloud.com/eumel8/test:e280436ecd7a21f1919bcb44e00ed936561e80f4 
INFO[2021-09-21T02:11:05Z] Pushed image to 1 destinations  
```

Sometimes the push failed and needs to retry:

```bash
INFO[2021-09-20T19:50:31Z] Pushing image to mtr.external.otc.telekomcloud.com/eumel8/test:8e1b08270d828afe1868f9268f90c278fc8c6612 
WARN[2021-09-20T19:55:33Z] Retrying operation after 1s due to Head "https://mtr.external.otc.telekomcloud.com/v2/eumel8/test/blobs/sha256:be1982caa7174a8b5189679500fe41e37ad41827ac1152199ff848cdc0cefa0c": unexpected EOF 
INFO[2021-09-20T19:55:36Z] Pushed image to 1 destinations  
```

**Expected behavior**
At the moment there are no information available what happened during the push process. A user output with some progress like in docker cli would be fine or a specific error message beside the "unexprected EOF".

**To Reproduce**
1. Use a big source image from 3 to 6 GB
2. Try to trigger a Gitlab Pipeline 

**Additional Information**
 - Dockerfile 
 ```bash
FROM nvcr.io/nvidia/clara/cheminformatics_demo:0.1.2
```
 - Build Context
   nothing else
 - Kaniko Image (fully qualified with digest)
 sha256:fcccd2ab9f3892e33fc7f2e950c8e4fc665e7a4c66f6a9d70b300d7a2103592f

- Referenced Write function while push https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/write.go#L48

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
