### ISSUE TITLE
GIT context with subfolders can not be set with args

### ISSUE THREAD

**Issue by ardacetinkaya** [GoogleContainerTools/kaniko#1755]
I am new to kaniko and have an issue. 
My project structure is like below in GitHub, I have another build pipeline which builds image as I expected.

```
/
-- SampleAPI
    - DockerFile
    - SampleAPI.csproj
    - .....
    - ...
-- SampleAPP
-- SomeOtherAPI
-- SomeAssets
-- .....
-- ...
```

And I have a pod for kaniko build:

```yaml
containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.0.0
        imagePullPolicy: Always
        args: ["--dockerfile=SampleAPI/Dockerfile",
                "--context=git://{SOME_GITHUB_REPO}.git",
                "--destination=SomeRegisteryInAzure.azurecr.io/kaniko-demo:v1",
                "--cache=true"]
```

But pod can not build my image, it gives an error saying that project file can not be found, probably because of context. I don't want to change existing Dockerfile content. But am I missing something?
