### ISSUE TITLE
build-args with spaces crash /kaniko/executor

### ISSUE THREAD

**Issue by dHannasch** [GoogleContainerTools/kaniko#1803]
For easy reproducibility, I've created https://gitlab.com/dHannasch/kaniko-build-arg-with-spaces following https://docs.gitlab.com/ee/ci/docker/using_kaniko.html .

I've made a modification to help show that what's running is exactly the same except for the `--build-arg`.

```
# copied from https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build_single_quote_with_spaces:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    BUILD_ARG: "--build-arg ABC='A B C'"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo "BUILD_ARG=$BUILD_ARG"
    - echo '/kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" $BUILD_ARG --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"'
    - echo "/kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile $BUILD_ARG --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      $BUILD_ARG
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

build_single_quote_without_spaces:
  extends: build_single_quote_with_spaces
  variables:
    BUILD_ARG: "--build-arg ABC='ABC'"

build_double_quote_without_spaces:
  extends: build_single_quote_with_spaces
  variables:
    BUILD_ARG: '--build-arg ABC="ABC"'

build_double_quote_with_spaces:
  extends: build_single_quote_with_spaces
  variables:
    BUILD_ARG: '--build-arg ABC="A B C"'
```

You can see at https://gitlab.com/dHannasch/kaniko-build-arg-with-spaces/-/pipelines that it doesn't matter whether we use single quotes or double quotes, but it does matter whether the build-arg contains spaces. When the build-arg contains spaces, we get `Error: unknown command "B" for "executor"`.

Presumably, this is getting parsed into `--build-arg`, `ABC="A`, `B`, and `C"`.
I gather that the Kaniko Docker image is based on golang:1.15 and the underlying shell is /busybox/sh, maybe that matters?

This may be related to https://github.com/GoogleContainerTools/kaniko/issues/1231 .

It looks like --build-arg is a VarP rather than a StringVarP, I'm not familiar enough with Cobra to know why that might be or whether it matters. (In the actual Dockerfile, build-args are always treated as strings, aren't they?)
https://github.com/GoogleContainerTools/kaniko/blob/master/cmd/executor/cmd/root.go#L186
```
	RootCmd.PersistentFlags().StringVarP(&opts.DockerfilePath, "dockerfile", "f", "Dockerfile", "Path to the dockerfile to be built.")
	RootCmd.PersistentFlags().StringVarP(&opts.CustomPlatform, "customPlatform", "", "", "Specify the build platform if different from the current host")
	RootCmd.PersistentFlags().VarP(&opts.BuildArgs, "build-arg", "", "This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.")
```
However, I don't think this actually matters, because the same parse error crops up if the DockerfilePath contains spaces. (To be clear, I do not think it matters that the Dockerfile path cannot contain spaces because *why would anybody ever do that*, but it seems like a --build-arg should be able to contain spaces.)

So maybe the problem is actually in Cobra itself, I'm not sure. I think /busybox/sh is just the default shell for the `golang` Docker image, right? But then again, there isn't a Cobra Docker image, whether based on `golang` or not, so maybe Cobra has some quirks when used with /busybox/sh, despite that being the default shell in the `golang` Docker image?

This may be related to https://github.com/spf13/cobra/issues/1114.

Incidentally, this is ultimately in service to allowing people to drop-in add a kaniko build with https://gitlab.com/shell-bootstrap-scripts/shell-bootstrap-scripts/-/blob/master/.gitlab-ci.yml#L7.
If kaniko cannot accept spaces directly, I suppose an alternative is to use some magic character to represent a space and, in the Dockerfile, convert that character back into a space wherever it appears in an ARG.

**Comment by Nh640** [comment]
Hi,

I'm having the same issue as you, but I managed to workaround this problem in this way:

`  script:
    - >-
      COMMAND="/kaniko/executor
      ${PODMAN_BUILD_ARGS}
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${CI_REGISTRY_IMAGE}/${IMAGE}:${VERSION}
      --destination ${CI_REGISTRY_IMAGE}/${IMAGE}:latest
      --context ${CI_PROJECT_DIR}"
    - eval "${COMMAND}"`

I don't know what is exactly causing the problem, but after a lot of testing I came across with this solution.

Regards.

**Comment by xenon-dev** [comment]
@Nh640 How do you variables look like then? I have the issue that e.g. "--dockerfile, --destination" and so on works, but the build arg variables are never even taking into account. I read from a custom variable that resides in GitLabs variable store.

**Comment by braykov** [comment]
I have hit the same issue, but trying to add labels where the value part has spaces (full sentences). I also struggled with all kind of quotes and escaping, etc, but just now I find this and realize it might be a kaniko CLI parsing bug.

**Comment by Nh640** [comment]
@xenon-dev I have declared my build arguments inside a file and I get its content using the following piece of code inside the gitlab-ci.yaml file:

```
before_script:
    - ...
    - KANIKO_BUILD_ARGS=$(awk '{printf "--build-arg %s ", $0 }' parameters/.env | awk '{$1=$1};1')
 ```

An example of the params file:

```
SYSTEM_REQUIREMENTS="shadow-utils hostname"
TOMCAT_XMS_PARAM_VALUE="2048m"
TOMCAT_XMX_PARAM_VALUE="4096m"
TOMCAT_PERMSIZE_PARAM_VALUE="256m"
TOMCAT_JMXREMOTE_PARAM_VALUE="true"
TOMCAT_JMXREMOTE_PORT_PARAM_VALUE="6569"
TOMCAT_JMXREMOTE_SSL_PARAM_VALUE="true"
```

**Comment by geudrik** [comment]
We also just hit this issue using `--build-arg MY_VAR_NAME="npm run-script install-subs"` results in a crash of `Error: unknown command "install\"" for "executor"`

**Comment by geudrik** [comment]
@Nh640 's suggestion doesn't appear to work sadly :/ 

We've got a couple hundred repo's that we manage, many of which have overrides that need to be passed into docker contexts. The solution that we've come up with is something akin to 

```yaml
build_staging:
  extends: .docker_build_and_publish
  variables:
    DOCKER_EXTRA_ARGS: "--build-arg NPM_DEP_INSTALL_CMD='npm install'"
```

That said, this solution currently doesn't seem to work, due to the above mentioned bug around spaces in those passed build-args.

**Comment by geudrik** [comment]
Alright, here's what we figured out that seems to work...

```dockerfile
ARG NPM_DEP_INSTALL_CMD
ARG NPM_BUILD_CMD

# Create our app builder dir
RUN mkdir /app

# Copy everything into our builder dir
COPY . /app

# These need to come from CI vars
RUN cd /app && $NPM_DEP_INSTALL_CMD && $NPM_BUILD_CMD
```

```yaml
build_staging:
  extends: .docker_build_and_publish
  variables:
    DOCKER_EXTRA_ARGS: '
    --build-arg NPM_DEP_INSTALL_CMD="npm install" 
    --build-arg NPM_BUILD_CMD="npm run-script build-staging" 
    '
```

```yaml
.docker_build_and_publish:
  stage: publish
  needs: [new_version_from_tag]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  script:
    - |
      ...
      
      echo "Setting IFS to null to avoid word splitting..."
      export IFS=''
 
      COMMAND="/kaniko/executor ${DOCKER_EXTRA_ARGS} --context $DOCKER_BUILD_CONTEXT --dockerfile $DOCKER_DOCKERFILE_DIR$DOCKER_DOCKERFILE_NAME$DOCKER_DOCKERFILE_EXTENSION --destination $DOCKER_IMAGE_NAME:$DOCKER_TAG_NAME $DOCKER_VERSION_TAG"

      echo "Running Kaniko command $COMMAND"
      eval "$COMMAND"
```
