### ISSUE TITLE
executable file not found in $PATH after build /usr/local/bin

### ISSUE THREAD

**Issue by geekbass** [GoogleContainerTools/kaniko#1820]
**Actual behavior**
It appears that Kaniko is ignoring the `/usr/local/bin` directory as part of the ignore list which contains the executable needed to run the app. Changes to this directory after a "RUN" is not being saved into the image. This caught me by surprise because the build and push complete successfully. Building with Docker works as expected but building with Kaniko completely empties the `/usr/local/bin` directory. 

Logs:
```
[1m[36mINFO[1m[0m[0001] Unpacking rootfs as cmd RUN apt-get update &&     apt-get install -y python3 python3-pip &&     pip3 install --upgrade pip
setuptools &&     rm -rf /root/.cache && rm -rf /var/cache/apt/* requires it.
[1m[37mDEBU[1m[0m[0001] Ignore list: [{/kaniko false} {/etc/mtab false} {/tmp/apt-key-gpghome true} {/var/run false} {/proc false} {/dev false} {/dev/pts false} {/sys false} {/sys/fs/cgroup false} {/sys/fs/cgroup/systemd false} {/sys/fs/cgroup/net_cls,net_prio false} {/sys/fs/cgroup/cpu,cpuacct false} {/sys/fs/cgroup/blkio false} {/sys/fs/cgroup/freezer false} {/sys/fs/cgroup/hugetlb false} {/sys/fs/cgroup/pids false} {/sys/fs/cgroup/memory false} {/sys/fs/cgroup/devices false} {/sys/fs/cgroup/perf_event false} {/sys/fs/cgroup/cpuset false} {/dev/mqueue false} {/work false} {/busybox false} {/dev/termination-log false} {/kaniko/.docker false} {/dev/shm false} {/etc/resolv.conf false} {/etc/hostname false} {/etc/hosts false} {/usr/local/bin false} {/var/run/secrets/kubernetes.io/serviceaccount false} {/var/run/secrets/eks.amazonaws.com/serviceaccount false} {/proc/bus false} {/proc/fs false} {/proc/irq false} {/proc/sys false} {/proc/sysrq-trigger false} {/proc/acpi false} {/proc/kcore false} {/proc/keys false} {/proc/latency_stats false} {/proc/timer_list false} {/proc/sched_debug false} {/sys/firmware false}]
[1m[37mDEBU[1m[0m[0001] Not adding /dev because it is ignored
[1m[37mDEBU[1m[0m[0001] Not adding /etc/hostname because it is ignored
[1m[37mDEBU[1m[0m[0001] Not adding /etc/resolv.conf because it is ignored
[1m[37mDEBU[1m[0m[0001] Not adding /proc because it is ignored
[1m[37mDEBU[1m[0m[0001] Not adding /sys because it is ignored
[1m[37mDEBU[1m[0m[0002] Not adding /usr/local/bin because it is ignored
[1m[37mDEBU[1m[0m[0002] Not adding /var/run because it is ignored
[1m[36mINFO[1m[0m[0002] RUN apt-get update &&     apt-get install -y python3 python3-pip &&     pip3 install --upgrade pip setuptools &&     rm -rf
 /root/.cache && rm -rf /var/cache/apt/*
[1m[36mINFO[1m[0m[0002] Taking snapshot of full filesystem...
...
LOTS OF PIP INSTALLING OF THINGS
...
...
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.20.9 botocore-1.23.9 jmespath-0.10.0 s3transfer-0.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommend
ed to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[1m[36mINFO[1m[0m[0068] Taking snapshot of full filesystem...
[1m[36mINFO[1m[0m[0082] EXPOSE 5000
[1m[36mINFO[1m[0m[0082] cmd: EXPOSE
[1m[36mINFO[1m[0m[0082] Adding exposed port: 5000/tcp
[1m[37mDEBU[1m[0m[0082] build: skipping snapshot for [EXPOSE 5000]
[1m[36mINFO[1m[0m[0082] ENTRYPOINT ["mlflow"]
[1m[37mDEBU[1m[0m[0082] build: skipping snapshot for [ENTRYPOINT ["mlflow"]]
[1m[37mDEBU[1m[0m[0082] mapping stage idx 0 to digest sha256:7b3784b252dd26197b5fa26e73074e0168181daf73f2a18a78f022a1ddbcaf75
[1m[37mDEBU[1m[0m[0082] mapping digest sha256:7b3784b252dd26197b5fa26e73074e0168181daf73f2a18a78f022a1ddbcaf75 to cachekey
[1m[36mINFO[1m[0m[0082] Pushing image to REGISTRY/mlflow:test
[1m[36mINFO[1m[0m[0098] Pushed image to 1 destinations
``` 
The build completes as successful but as mentioned none on the executables exist in the `/usr/local/bin/` directory.

```
> docker run  registry/mlflow:test
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "mlflow": executable file not found in $PATH: unknown.

> docker run -it  --entrypoint=/bin/bash registry/mlflow:test
root@f45da9eb7ec8:/# mlflow
bash: mlflow: command not found
root@f45da9eb7ec8:/# ls -l /usr/local/bin/
total 0

```
**Expected behavior**
I expect that there would be several files that exist in the `/usr/local/bin` directory as this is the place where several packages and executables are being installed during the image build. The files are just completely missing after the build. 

**To Reproduce**
1. The build is run as part of an Argo Workflow DAG. The Kaniko step is shown below in the Build Context. 

**Additional Information**
 - Dockerfile 
 ```
FROM debian:buster-20211115-slim
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /root/.cache && rm -rf /var/cache/apt/*
RUN pip install mlflow && \
    pip install scikit-learn && \
    pip install psycopg2-binary && \
    pip install boto3
EXPOSE 5000
ENTRYPOINT ["mlflow"]
```
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
```
- name: build-mlflow
      inputs:
        artifacts:
          - name: clone-source
            path: /work
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.branch}}"
              insecureIgnoreHostKey: true
              sshPrivateKeySecret:
                name: github-creds
                key: ssh-private-key
        parameters:
          - name: tag
          - name: repo
          - name: branch
          - name: account
          - name: region
      volumes:
        - name: docker-config
          configMap:
            name: docker-config
      container:
        volumeMounts:
          - mountPath: /usr/local/bin
            name: ecr-login
          - name: docker-config
            mountPath: /kaniko/.docker
        image: gcr.io/kaniko-project/executor:v1.7.0-debug
        env:
          - name: AWS_SDK_LOAD_CONFIG
            value: "false"
        args:
          - --verbosity=debug
          - --dockerfile=./Dockerfile
          - --context=dir:///work/kubernetes/mlflow/
          - --destination={{inputs.parameters.account}}.dkr.ecr.{{inputs.parameters.region}}.amazonaws.com/mlflow:{{inputs.parameters.tag}}
      initContainers:
        - name: ecr-login
          image: busybox:1.34.1
          command:
            - chmod
          args:
            - +x
            - /usr/local/bin/docker-credential-ecr-login
          mirrorVolumeMounts: true
```
 - Kaniko Image (fully qualified with digest) `v1.7.0` 
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
