### ISSUE TITLE
Error checking push permissions on kaniko v1.7.0

### ISSUE THREAD

**Issue by fg91** [GoogleContainerTools/kaniko#1821]
**Actual behavior**

When upgrading from v1.6.0 to v1.7.0 our CI starts failing with the following error message:

```
gcr.io/kaniko-project/executor:v1.7.0
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "gcr.io/mx-labs-devops/mx-devtool-labs:c3cf4e4": creating push check transport for gcr.io failed: GET https://gcr.io/v2/token?scope=repository%3Amx-labs-devops%2Fmx-devtool-labs%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: Not Authorized.
```

Nothing else has been changed.

**Expected behavior**

With v1.6.0 there haven't been any permission related errors.

**To Reproduce**

We used to following step in cloudbuild:

```yaml
  - name: gcr.io/kaniko-project/executor:v1.6.0
    args:
      - --dockerfile=./infrastructure/docker/Dockerfile
      - --use-new-run
      - --cache=false
      - --cache-ttl=${_CACHE_TTL}
      - --destination=${_IMAGE_NAME}:${SHORT_SHA}
    volumes:
      - name: home
        path: /root
    id: build_base
```

The error occurred upon increasing the version to v1.7.0.

**Additional Information**

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
