### ISSUE TITLE
Automate assigning docker image tag.

### ISSUE THREAD

**Issue by nishit93-hub** [GoogleContainerTools/kaniko#1886]
Hi There,
I am running a Argo workflow to create docker images using Kaniko image builder . Below is the shortcode.

```
   container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
        - "--context=dir:///workspace"
        - "--destination=dockerimage:1.0"
```

Every time I run this workflow, before that I have to update the image tag manually, to create a docker image with new tags. Is there any way I can automate this?
