### ISSUE TITLE
Can't inject AWS credentials file into Kaniko because /root/.aws/ directory doesn't exist

### ISSUE THREAD

**Issue by pcgeek86** [GoogleContainerTools/kaniko#1943]
**Actual behavior**

Can't mount / inject AWS credentials file into Kaniko, because `/root/.aws/` directory does not exist.
There is also no shell inside the Kaniko container, so I could call the `mkdir` command.
There's also no option on Kaniko to override the default filesystem location of the AWS credentials file.

**Net result:** I cannot mount the AWS credentials file into the Kaniko container.

```
Error: failed to start container "kaniko": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/kubelet/pods/dcfce755-76ee-4436-b9d3-f22f3b6336c3/volume-subpaths/aws-ecr/kaniko/0" to rootfs at "/root/.aws" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Expected behavior**

AWS credentials is mounted into the container under `/root/.aws/`.

**To Reproduce**

```
apiVersion: v1
kind: Secret
metadata:
  name: gitlabtoken
type: Opaque
stringData:
  password: xxxxxxxxxxxxxx
  username: xxxxxxxxxxxxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr
stringData:
  credentials: |
    [default]
    aws_access_key_id=xxxxxxxxxxxxxxx
    aws_session_token=xxxxxxxxxxxxxx
    region=us-west-2
    aws_secret_access_key=xxxxxxxxxxx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
data:
  config.json: |
    { "credsStore": "ecr-login" }
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  volumes:
  - name: docker-config
    configMap:
      name: docker-config
  - name: aws-ecr
    secret:
      secretName: aws-ecr
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
    - name: aws-ecr
      mountPath: /root/.aws/
      subPath: credentials
    - name: docker-config
      mountPath: /kaniko/.docker/
      subPath: config.json
    env:
      - name: GIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gitlabtoken
            key: password
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            name: gitlabtoken
            key: username
    args:
    - "--dockerfile=Dockerfile"
    - "--context=git://gitlab.com/trevorsullivan/helm-pwsh-pode.git"
    - "--context-sub-path=pwshpode-app"
    - "--destination=987868780346.dkr.ecr.us-west-2.amazonaws.com/helm-pwsh-pode:v5"
---
```

**Additional Information**
 - Dockerfile n/a

 - Build Context n/a see above
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest) docker-pullable://987868780346.dkr.ecr.us-west-2.amazonaws.com/kaniko@sha256:9eabf283db61ddb8f6c598f4afe53a4efcca833d800710408cbf161740bacb48
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
