### ISSUE TITLE
Latest release regresses OCI layout support

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/kaniko#1974]
**Actual behavior**

With the latest release (last night), some of our e2e tests fail with:

```
INFO[0000] CMD ["echo Hello World"]                     
INFO[0001] Skipping push to container registry due to --no-push flag 

Error: open /var/run/oci/layout/blobs/sha256/c6f4d1a13b699c8490910fd4fd6c7056b90fd0da3077e4f29b4bd27bf0bae6cd: permission denied
```

**Expected behavior**

This passed with `:latest` prior to the v1.8.0 cut, which according to @imjasonh was v1.6.0.

**To Reproduce**

These are the two relevant steps of the Tekton task whose output you see above:

```yaml
    - name: build-as-layout
      image: gcr.io/kaniko-project/executor:latest
      args:
      - --dockerfile=/workspace/$(params.path)/$(params.dockerfile)
      - --context=/workspace
      - --no-push # We are writing a layout
      - --oci-layout-path=/var/run/oci/layout
      - --digest-file=/tekton/results/dev.mink.images.digest
      - $(params.kaniko-args)
      volumeMounts:
      - name: oci-layout
        mountPath: /var/run/oci/layout

    - name: push-layout
      image: gcr.io/go-containerregistry/krane:latest
      args: ["push", "--image-refs=/tekton/results/IMAGES", "/var/run/oci/layout", "$(params['dev.mink.images.target'])"]
      volumeMounts:
      - name: oci-layout
        mountPath: /var/run/oci/layout
```

Here `krane` *used* to be able to read the layout and publish it (it is `:nonroot`), but something about the latest release is causing the permission denied error above.

Pinning to v1.7.0 "fixed" this for us, which narrows the window of regression to sometime in v1.8.0.

**Additional Information**

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
