### ISSUE TITLE
Kaniko executor command on GitLab CI fails with "/kaniko/Dockerfile: copy_file_range: is a directory" when using variable expansion across parent-child pipelines

### ISSUE THREAD

**Issue by that1francisco** [GoogleContainerTools/kaniko#2086]
**Actual behavior**
When using variable expansion across parent-child pipelines on GitLab CI, Kaniko interprets the name of the Dockerfile as a directory.

**Expected behavior**
A variable defined in a parent pipeline should be correctly interpreted in the child pipeline's Kaniko job.

**To Reproduce**
1. Define a variable in the parent pipeline like so:

`variables:
    DOCKERFILE: Dockerfile`

Also works with `DOCKERFILE: "Dockerfile"`

2. Call this variable in the child pipeline when building the Kaniko job.

**Additional Information**
 - The child pipeline was a nested child -> i.e. the variable is defined in the parent, the child triggered another pipeline and in this second child is where the Kaniko build job is running.
 - The Dockerfile in question is in a directory (dashboard/base-build)
 - Parent Pipeline (.gitlab-ci.yml)
```
stages:
  - build

# Default / common variables
variables:
  IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  LATEST_TAG: latest

dashboard:
  stage: build
  rules:
    - changes:
        - common/*
  trigger:
    include: dashboard/.dashboard-ci.yml
```

 - Child Pipeline YAML (dashboard/.dashboard-ci.yml)
```
stages:
  - base-build

# Jobs
base-build:
  stage: base-build
  variables:
    IMAGE_NAME: "$IMAGE_NAME_DASHBOARD_BASE"
    CONTEXT: "dashboard/base-build"
  trigger:
    include: common/.build-ci.yml
    strategy: depend
```

 - Nested Child Pipeline YAML (common/.build-ci.yml)
 **If I replace "${DOCKERFILE}" with Dockerfile, it starts the build normally.**
```
stages:
  - build

# Default variables
variables:
  CONTEXT: "./"

# Gitlab Anchor called &kaniko-build
.kaniko-build: &kaniko-build
  - |
    /kaniko/executor --context "${CONTEXT}" \
    --dockerfile "${DOCKERFILE}" \
    --destination "${REMOTE_IMAGE_REF}" \
    --destination "${LATEST_REMOTE_IMAGE_REF}"

# Jobs
build:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.8.1-debug
    entrypoint: [""]
  variables:
    REMOTE_IMAGE_REF: '${DOCKER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}'
    LATEST_REMOTE_IMAGE_REF: '${DOCKER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${LATEST_TAG}'
  before_script:
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
  script:
    - *kaniko-build
```
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ no ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [not applicable] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ no ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ no ] </li></ul>|
