### ISSUE TITLE
unable to push to docker hub from GKE Pod

### ISSUE THREAD

**Issue by sebgoa** [GoogleContainerTools/kaniko#239]
Hi,

I can use kaniko just fine on a local docker for mac installation. and I wrote:
https://medium.com/@sebgoa/building-docker-images-with-kaniko-6e2421b018

Now I try to setup a cronjob to run the same kaniko build within a GKE cluster. I use:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: build
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init
            image: gcr.io/cloud-builders/git 
            args:
            - "clone"
            - "https://github.com/sebgoa/functions.git"
            - "/tmp"
            volumeMounts:
            - name: source
              mountPath: /tmp
          - name: ls
            image: debian:stable-slim
            command: ["/bin/sh"]
            args:
            - "-c"
            - "cat /tmp/config.json"
            volumeMounts:
            - name: docker
              mountPath: /tmp/
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:latest
            args: ["--destination=index.docker.io/runseb/barbaz"]
            env:
            - name: DOCKER_CONFIG
              value: /secret
            volumeMounts:
            - name: source
              mountPath: /workspace
            - name: docker
              mountPath: /secret
          restartPolicy: OnFailure
          volumes:
          - name: source
            emptyDir: {}
          - name: docker
            configMap:
              name: docker
```

Have tried tons of things, but the closest I get is this error:

```
kubectl logs build-1531916940-7l6xt -c kaniko 
time="2018-07-18T12:29:56Z" level=info msg="Unpacking filesystem of kubeless/python:3.6..."
time="2018-07-18T12:29:56Z" level=error msg="Get https://index.docker.io/v2/: EOF"
```

My `config.json` use `/v1` for the registry url, but here I get an error relating to `v2`.

Is it a kaniko thing ? or a GKE thing ?

**Comment by sebgoa** [comment]
what is very weird is that sometimes I also get a connection refused error:

```
$ kubectl logs build-1531918860-h94vl -c kaniko
time="2018-07-18T13:01:09Z" level=info msg="Unpacking filesystem of kubeless/python:3.6..."
time="2018-07-18T13:01:09Z" level=error msg="Get https://index.docker.io/v2/: dial tcp 34.203.15.50:443: connect: connection refused"
```

I do have calico installed in GKE, but I don't have any network policies setup.

I also ssh'd in one of the GCE instances that make up the GKE cluster and did the same `docker run` command that I do locally, and the build worked fine and was able to push.

**Comment by priyawadhwa** [comment]
Hey @sebgoa, thanks for writing the article! I tried to run a similar cronjob:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: build
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init
            image: gcr.io/cloud-builders/git 
            args:
            - "clone"
            - "https://github.com/GoogleContainerTools/kaniko.git"
            - "/tmp"
            volumeMounts:
            - name: source
              mountPath: /tmp
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:eb6faa05a023835205f901dee32b28f827208103
            args: ["--dockerfile=dockerfiles/Dockerfile_test_multistage", "--context=/workspace/integration","--destination=gcr.io/priya-wadhwa/test:test"]
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/kaniko-secret.json
            volumeMounts:
            - name: source
              mountPath: /workspace
            - name: kaniko-secret
              mountPath: /secret
          restartPolicy: OnFailure
          volumes:
          - name: source
            emptyDir: {}
          - name: kaniko-secret
            secret:
              secretName: kaniko-secret
```
which was able to build successfully. 

I was also able to pull in ` kubeless/python:3.6` without mounting in any special credentials, so I think it must be an issue with your `config.json`, since I'm pretty sure go-containerregistry, which kaniko uses to pull in images, assumes you're trying to pull a `v2` image.
