### ISSUE TITLE
Kanibo's debug POD can't be launched - stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by cmoulliard** [GoogleContainerTools/kaniko#246]
If I try to create a debug's pod using this resource's definition to debug kanibo, then it fails

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - "/busybox/sh"
    volumeMounts:
    - name: build-data
      mountPath: /var/lib/kaniko/data
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  restartPolicy: Never
```

Error

```
rpc error: code = 2 desc = oci runtime error: 
exec failed: container_linux.go:247: starting container process caused
 "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

command terminated with non-zero exit code: Error executing in Docker Container: 126
```
