### ISSUE TITLE
kaniko could not push to local gitlab registry with error "registries must be valid RFC 3986 URI authorities:  gitlab.gitlab:5000"

### ISSUE THREAD

**Issue by tweakmy** [GoogleContainerTools/kaniko#248]
Hi, 
I am running a local private registry on a private kubernetes cluster. I am a step away from having full ci/cd.
kubernetes dns could resolved to gitlab.gitlab but not sure this dnsname in certficate was wrong when I setup in Kubernetes. Can this be fix? Is there an overwrite?

**Comment by tweakmy** [comment]
In case anyone is wondering how the kaniko was run

```
apiVersion: v1
kind: Pod
metadata:
  name: build
  namespace: gitlab
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: nginx
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    env:
      - name: DOCKER_CONFIG
        value: "/kaniko"
    args:
      - -d gitlab.gitlab:5000/root/awesome-project
    volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: config
        mountPath: /kaniko/config.json
      - name: cacert
        mountPath: /kaniko/ssl/certs/ca-certificates.crt
  volumes:
    - name: workspace
      hostPath:
         # directory location on host
         path: /home/tweakmy/spin-kub-demo
         # this field is optional
         type: Directory
    - name: config
      hostPath:
         # directory location on host
         path: /home/tweakmy/spin-kub-demo/config.json
    - name: cacert
      hostPath:
         # directory location on host
         path: /home/tweakmy/cloud/Gitlab/tls/ca.crt
```

**Comment by chrisz100** [comment]
@tweakmy can you try prefixing the registry url with // ? 
kaniko validates against that - as you can see here: 
https://github.com/google/go-containerregistry/blob/master/pkg/name/registry.go#L89

**Comment by gperdomor** [comment]
According to gitlab docs: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

```yaml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
```

I got this error:

`Error: failed to push to destination registry.gitlab.com/alliotek/alliot-platform/account-api:latest: no token in bearer response:
{"errors":[{"code":"DENIED","message":"access forbidden"}],"http_status":403}
`
