### ISSUE TITLE
GCP Artifact Registry push error from Gitlab -- Permission error

### ISSUE THREAD

**Issue by Aba007** [GoogleContainerTools/kaniko#2549]
Hello,

I am trying to push to my GCP registry but I keep getting permission error. I believe I am using the appropriate image but it still wont let me push.

````
docker-build:
  stage: package
  variables:
    ACCESS_TOKEN: $ACCESS_TOKEN
    # GOOGLE_APPLICATION_CREDENTIALS: GOOGLE_SERVICE_ACCOUNT_JSON
  tags:
    - metalingo
  services:
    - docker:dind
  image:
    name: gcr.io/kaniko-project/executor:a7425d1fd0442b58dc24698285102176365a28d9-debug
    entrypoint: [""]
  before_script:
    - cp $GOOGLE_SERVICE_ACCOUNT_JSON /kaniko/.docker/config.json
    - docker-credential-gcr configure-docker --registries=northamerica-northeast2-docker.pkg.dev
    - echo "Tag "${CI_COMMIT_SHORT_SHA}
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "northamerica-northeast2-docker.pkg.dev/project007/image_bond/${CI_COMMIT_SHORT_SHA}"
      # --no-push
  only:
    - main
````

I get the following error:

````
$ /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "northamerica-northeast2-docker.pkg.dev/project007/image_bond/${CI_COMMIT_SHORT_SHA}" 

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: 

checking push permission for "northamerica-northeast2-docker.pkg.dev/project007/image_bond/2cdc890b": 

creating push check transport for northamerica-northeast2-docker.pkg.dev failed: GET https://northamerica-northeast2-docker.pkg.dev/v2/token?scope=repository%3Aproject007%2Fimage_bond%2F2cdc890b%3Apush%2Cpull&service=northamerica-northeast2-docker.pkg.dev: 

UNAUTHORIZED: authentication failed
````

**Comment by Aba007** [comment]
Here's the error again:

`
$ /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "northamerica-northeast2-docker.pkg.dev/project007/image_bond/${CI_COMMIT_SHORT_SHA}"
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "northamerica-northeast2-docker.pkg.dev/project007/image_bond/099723fd": resolving authorization for northamerica-northeast2-docker.pkg.dev failed: error getting credentials - err: exit status 1, out: `docker-credential-gcr/helper: could not retrieve GCR's access token: google: error getting credentials using
`

**Comment by erikdao** [comment]
@Aba007 Hi, did you resolve this issue? I'm having a similar issue but with GitHub Actions.

**Comment by Aba007** [comment]
Hello @erikdao - I honestly can't remember for the life of me.

I believe the issue was with the variable $GOOGLE_SERVICE_ACCOUNT_JSON. I believe it was one of the following reasons:

1) I had set at either file or variable (check your type field)
2) The service account that the key was based on didn't have the right information in GCP
3) How i was passing the SA into kaniko at the time

But it's been working for years now. I have seen this error a few times and it's almost always been related to the variable. If you're using a separate account, make sure the password and everything else still works for it. I'd eliminate that first. 

```
docker-build:
  stage: package
  variables:
    ACCESS_TOKEN: $ACCESS_TOKEN
  tags:
    - runner_tag
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]
  before_script:
    - echo $GOOGLE_SERVICE_ACCOUNT_JSON /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "northamerica-northeast2-docker.pkg.dev/project/repo_name/folder:${PROJECT_VERSION}"
  only:
    - main
```
