### ISSUE TITLE
Proposal: Automatically close inactive issues

### ISSUE THREAD

**Issue by ferrastas** [GoogleContainerTools/kaniko#2551]
**Proposal**
This project has 559 open issues at the moment of writing this one, some of them are back from 2018 and several of them are waiting for feedback from the person that opened it. It is not fair for the project's maintainers as might show a lack of attention to the project. 
To solve that I propose using https://github.com/marketplace/actions/close-stale-issues to automatically send a message to stale issues and close them if there is no further feedback from the issue's author. There is more info here https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

I can open a PR myself but I do not have the powers to create an additional project token and store it as a secret.

This seems to be a good starting configuration, setting `days-before-pr-close` as `-1` will not close open/stale PRs, 30 days for stale and 15 days for removal are just values that I consider acceptable, each issue creator has 45 days to interact with the issue before closing.

```
name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 15 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 15 days with no activity.'
          days-before-stale: 30
          days-before-close: 15
          days-before-pr-close: -1
```
