### ISSUE TITLE
--tar-path unknown flag error

### ISSUE THREAD

**Issue by ConfusB** [GoogleContainerTools/kaniko#2643]
**Actual behavior**
Kaniko executor doesn't understand --tar-path argument

**Expected behavior**
I would like to build a tar path

**To Reproduce**
1. apply this settings
```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-286592
  namespace: azure-devops-agents
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=Dockerfile"
    - '--context=dir:///workspace/api-template'
    - "--tar-path image.tar"
    - "--no-push"
    - "--destination=image"
    - "--build-arg=password=pass"
    - "--build-arg=kanikoBuild=true"
    env:
      - name: AWS_SDK_LOAD_CONFIG
        value: "true"
      - name: AWS_EC2_METADATA_DISABLED
        value: "true"
    envFrom:
    - secretRef:
        name: "secret"
    - secretRef:
        name: "api-template"
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
    - name: source-code
      mountPath: /workspace
    - name: pvc-kaniko-cache
      mountPath: /cache`
```
2. Get this error:
```
Error: unknown flag: --tar-path image.tar
Usage:
  executor [flags]
r [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  version     Print the version number of kaniko

Flags:
      --build-arg multi-arg type                  This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
      --cache                                     Use cache when building image
      --cache-copy-layers                         Caches copy layers
      --cache-dir string                          Specify a local directory to use as a cache. (default "/cache")
      --cache-repo string                         Specify a repository to use as a cache, otherwise one will be inferred from the destination provided; when prefixed with 'oci:' the repository will be written in OCI image layout format at the path provided
      --cache-run-layers                          Caches run layers (default true)
      --cache-ttl duration                        Cache timeout, requires value and unit of duration -> ex: 6h. Defaults to two weeks. (default 336h0m0s)
      --cleanup                                   Clean the filesystem at the end
      --compressed-caching                        Compress the cached layers. Decreases build time, but increases memory usage. (default true)
      --compression compression                   Compression algorithm (gzip, zstd)
```

**Additional Information**
 - Dockerfile 
```
FROM mcr.microsoft.com/dotnet/sdk:6.00 AS build
WORKDIR /src

ARG password
COPY . .
RUN dotnet nuget update source Artifactory --password $password --store-password-in-clear-text --username nuget-reader --configfile "NuGet.Config"

RUN dotnet restore --no-cache --configfile "NuGet.Config" *.sln

RUN dotnet publish *.sln -c Release --no-restore -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
RUN groupadd -g 1000 appgroup && useradd -u 1000 -g appgroup -s /bin/bash -m appuser

COPY --from=build /app .
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
RUN chown -R appuser:appgroup /app
USER appuser
EXPOSE 80

ENTRYPOINT ["/app/entrypoint.sh"]
```

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [No] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [Yes] </li></ul>|
