### ISSUE TITLE
[BUG] Kaniko deletes necessary generated files

### ISSUE THREAD

**Issue by droslean** [GoogleContainerTools/kaniko#2714]
**Actual behavior**
I am building a next.js project inside my Dockerfile. When I build my image using podman or docker, everything is just fine.

When I am building the image using Kaniko, there are missing files, invalidating the image since it cannot be used.

For example, the building of a next.js project generates a file `BUILD_ID` in the `.next` folder. This is required for the application to start. Kaniko is deleting that file.

```yaml
        command:
        - /kaniko/executor
        args:
        - --dockerfile=Dockerfile
        - --context=.
        - --destination=my-destination-image:my-tag
        - --cache=true
        - --cache-dir=/cache
        - --compressed-caching=false
        - --use-new-run
        - --cleanup
```

**Expected behavior**
I would expect `Kaniko` not to touch the files that are being generated by my commands in the Dockerfile.

**Additional Information**
 - Dockerfile 
```
FROM node:18.12.1-alpine AS build-stage

WORKDIR /app

COPY . .
RUN yarn install --frozen-lockfile
RUN yarn build


FROM node:18.12.1-alpine AS run-stage

WORKDIR /app

COPY --from=build-stage /app/.next ./.next
COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/package.json ./package.json
COPY --from=build-stage /app/public ./public

CMD ["yarn", "start"]

```
 - Kaniko Image (fully qualified with digest)
  `gcr.io/kaniko-project/executor:latest`
