### ISSUE TITLE
Pushing with kaniko is slow

### ISSUE THREAD

**Issue by suleimi** [GoogleContainerTools/kaniko#2751]
**Actual behavior**
Pushing large images (e.g 5Gb) with kaniko to some https registries (e.g ecr, quay or gitlab contianer registry) has been identified to be quite slow when using kaniko . After some preliminary investigation (in https://gitlab.com/gitlab-org/gitlab/-/issues/241996 )it appears the slowness comes from the issue mentioned in https://github.com/golang/go/issues/47840 and is related to the http/2 implementation of `net/http` 

Because of the slowness caused by https://github.com/golang/go/issues/47840 docker and buildx registry clients have opted to only push on http/1.1 connection. see: https://github.com/moby/buildkit/pull/1420

A few issues have been raised on (go-containerregistry) which kaniko uses that alludes to a similar http2 bottleneck:

- https://github.com/google/go-containerregistry/issues/1193
- https://github.com/google/go-containerregistry/issues/1210

**Expected behavior**

Pushing a 5Gb layer using kaniko to gitlab contianer registry, ecr or quay  should not take > 30mins on arguably fast internet connections

**To Reproduce**
1. Push a random 5Gb image to gitlab container registry 
2. Push a random 5Gb image to gitlab container registry with http 2 disabled (by setting GODEBUG="http2client=0")
3. Observe it takes almost > 40mins with http 2 enabled

**Additional Information**
 - Setup: https://gitlab.com/suleimiahmed/registry-speed-test/-/tree/test-ff?ref_type=heads
     -  includes docker file
     - Any kaniko that defaults to http 2 has this issue
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by slamer59** [comment]
From 40 minutes to 2 minutes... Thanks !

**Comment by stocktondr** [comment]
> From 40 minutes to 2 minutes with workaround... Thanks !

We are having the same problem.
The workaround also worked for us.

**Comment by zijiwork** [comment]
How to solve the problem of slow push in tekton kaniko

**Comment by keepdying** [comment]
We also saw improvements on builds while pushing caches and image to gcr and gar. From 13 mins to 7 mins.
Thanks for workaround!

**Comment by psarka** [comment]
In my case it went from 38min to 2min. @zijiwork this is how you do it in gitlab:

```
build-ci-image:
    stage: build-ci-image
    variables:
         GODEBUG: "http2client=0"
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint: [ "" ]
    script:
        - /kaniko/executor
            --context ...
            --dockerfile ...
            --destination ...
```

**Comment by aapjeisbaas** [comment]
Uploads to gitlab registry went from max 5 mbit/s to full line speed
```yaml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    GODEBUG: "http2client=0"
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
```
