### ISSUE TITLE
Kaniko builds ignore all environment variables

### ISSUE THREAD

**Issue by droslean** [GoogleContainerTools/kaniko#2824]
**Actual behavior**
```yaml
  containers:
  - args:
    - --dockerfile=Dockerfile
    - --context=.
    - --destination=ghcr.io/org/repo/image:tag
    - --cache=true
    - --cache-dir=/cache
    - --compressed-caching=false
    - --snapshot-mode=redo
    command:
    - /kaniko/executor
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    name: kaniko
    env:
    - name: YARN_PROXY
      value: http://npm-proxy-cache.ci
```

P.S. I also tried to pass a `--build-arg=YARN_PROXY=whatever.com` but the problem persists.

The scripts can't find the YARN_PROXY env var.

**Expected behavior**
The env vars should be resolved.

**To Reproduce**
1. Create a build for a Dockerfile that runs a script to operate on a specific env var value.

**Additional Information**
 - Dockerfile 
```dockerfile
FROM node:18.12.1-alpine
RUN my_script.sh
```

my_script.sh
```sh
#!/bin/sh
set -x
set -e

if [ -n "$YARN_PROXY" ]; then
    echo "Configuring Yarn to use proxy: $YARN_PROXY"
    
    yarn config set proxy "$YARN_PROXY"
    yarn config set https-proxy "$YARN_PROXY"
else
    echo "YARN_PROXY is not defined. Skipping proxy configuration."
fi
```
