### ISSUE TITLE
allow to set DOCKER_CONFIG to a file

### ISSUE THREAD

**Issue by sebhoss** [GoogleContainerTools/kaniko#2894]
We are using GitLab CI pipelines and would like to set `DOCKER_CONFIG` to a file instead of a directory so that we can use CI variables of type `file`. The current working approach in GitLab looks similar to this (see [official docs](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html)):

```yaml
build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${USER}" "${PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor ...
```

The above examples requires 3 variables (REGISTRY, USER, PASSWORD) to write a file into the kaniko container. We can use [file](https://docs.gitlab.com/ee/ci/variables/#use-file-type-cicd-variables) variables to reduce this to:

```yaml
build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: ${DOCKER_CONFIG_JSON}
  script:
    - /kaniko/executor ...
```

In this example, DOCKER_CONFIG_JSON is the file variable which contains the entire JSON document. GitLab will automatically add that file to the container and populate the `DOCKER_CONFIG_JSON` value with the path to the created file.

I have noticed that there is https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/util/gcr_util.go which does the right thing(tm) but does not appear to be used anywhere. The various other places where `DOCKER_CONFIG` is read all assume that it is a directory.
