### ISSUE TITLE
v1.19.1 still have AWS ECR authentication problem

### ISSUE THREAD

**Issue by fshiori** [GoogleContainerTools/kaniko#2906]
**Actual behavior**
unexpected status code 401 Unauthorized: Not Authorized

**Expected behavior**
Push image okay.

**To Reproduce**

**Additional Information**
```
   image:
     name: gcr.io/kaniko-project/executor:v1.19.1-debug
     entrypoint: [""]
   cache: {}
   before_script: []
   script:
     - mkdir -p /kaniko/.docker
     - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
     - /kaniko/executor --snapshot-mode=time --single-snapshot --use-new-run --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/build/Dockerfile --destination $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE/$COMPONENT:latest --destination $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ No ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ Yes ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ No ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ Yes ] </li></ul>|
