### ISSUE TITLE
Issue with building Kaniko

### ISSUE THREAD

**Issue by firstval** [GoogleContainerTools/kaniko#2993]
This is my ci file
```
build-stg:
  stage: build-stg
  script:
   - export PATH="$PATH:/usr/local/bin/"
   - export AWS_REGION="ap-southeast-1"
# Copy the NPM Config settings to Build Dir
   - echo "===== INIT ====="
   - source /usr/local/nvm/nvm.sh
   - echo "===== SET NODE VERSION ====="
   - npm cache clean --force
   - cp /home/gitlab-runner/.npmrc .
   - echo "===== BUILD STG INTER ====="
   - echo "*******RUNNING NPM CI*******"
   - npm ci
   - echo "*******FINISHED NPM CI*******"
   - echo "*******RUNNING NPM RUN*******"
   - CI=false npm run build-staging
   - echo "*******FINISHED NPM RUN*******"

   - mkdir stg
   - cp -r client stg/
   - cp -v $STG_DOCKER_FILE stg/
   - cp -v package* stg/
   - ls -ltr stg/

   - echo "===== STG INTER BUILD DOCKER IMAGE ====="
   - cd stg
   - IMG_ENV='s'
   - |
    if [ -n "$(find . -type f -name 'pyproject.toml' -exec grep -m 1 'version =' {} \;)" ]; then
      VERSION=$(find . -type f -name 'pyproject.toml' -exec grep -m 1 'version =' {} \; | sed 's/version =//;s/["'\'']//g' | tr -d ' ' | head -n 1)
    elif [ -n "$(find . -type f -name 'package.json' -exec jq -r '.version' {} \;)" ]; then
      VERSION=$(find . -type f -name 'package.json' -exec jq -r '.version' {} \; | head -n 1)
    else
      echo 'Neither package.json nor pyproject.toml found. Exiting...'
      exit 1
    fi
    export VERSION="$VERSION$IMG_ENV"
   - echo "VERSION:$VERSION"

   - echo "===== $APP_NAME:$VERSION ====="

   - echo "===== UPLOAD IMAGE  ====="
   - /kaniko/executor
     --context "${CI_PROJECT_DIR}"
     --dockerfile "${CI_PROJECT_DIR}/$STG_DOCKER_FILE"
     --destination "$APP_NAME:$VERSION"
     --cache=true
```

Dockerfile
```
FROM node:14.15.0-alpine

WORKDIR /opt/mol-va-vica-admin

COPY client ./client

EXPOSE 3000

RUN npm install -g serve

CMD serve -s -p 3000 client/build

```

Now my issue is the build is finished without any issues or errors, but when I run the images using `docker run` that have been built by Kaniko, it shows this error: 
> /bin/sh: serve: not found

while building using docker this is the output shows :
```
 ERROR  Cannot copy server address to clipboard: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel.

   ┌────────────────────────────────────────┐
   │                                        │
   │   Serving!                             │
   │                                        │
   │   - Local:    http://localhost:3000    │
   │   - Network:  http://172.17.0.4:3000   │
   │                                        │
   └────────────────────────────────────────┘
```

So it means Kaniko doesn't run the serve please help me to solve this issue
I'm using this kaniko version `gcr.io/kaniko-project/executor:v1.20.0-debug`
