### ISSUE TITLE
Azure Blob Storage Context invalid path

### ISSUE THREAD

**Issue by herveleclerc** [GoogleContainerTools/kaniko#3044]
It seems that the path to get the context is wrong when using azure blob storage container

ex :

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=./Dockerfile",
            "--context=https://kanikoi0skbb6wot.blob.core.windows.net/kaniko/context.tar.gz",
            "--destination=herveleclerc/kaniko-hello:0.0.1", "--verbosity=trace"]
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    env:
    - name: AZURE_STORAGE_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: azure-storage-access-key
          key: azure-storage-access-key
  volumes:
  - name: azure-storage-access-key
    secret:
      secretName: azure-storage-access-key
  - name: kaniko-secret
    secret:
      secretName: dockerhub
      items:
      - key: .dockerconfigjson
        path: config.json
```

generate this error log

```
k logs kaniko
DEBU[0000] Getting source context from https://kanikoi0skbb6wot.blob.core.windows.net/kaniko/context.tar.gz
DEBU[0000] BaseDir /kaniko/buildcontext for file /kaniko/buildcontext/context.tar.gz does not exist. Creating.
Error: error resolving source context: HEAD https://kanikoi0skbb6wot.blob.core.windows.net/kaniko/context.tar.gz/kaniko/context.tar.gz
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified blob does not exist.
ERROR CODE: BlobNotFound
--------------------------------------------------------------------------------
Response contained no body
--------------------------------------------------------------------------------
```

the path name is in double
