### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by WolfspiritM** [GoogleContainerTools/kaniko#309]
Hi,

We're currently using docker-compose to layout our microservice architecture.
Our CI/CD server just executes a docker-compose build and a docker-compose push to build and push the images within a docker-in-docker environment. I'd like to switch that to kaniko, but I don't like to specifiy each Dockerfile individually.
I know that google is not using docker compose but it would be great if kaniko would be able to read (and merge) docker-compose files and use the build informations contained in there to build and push multiple images at once.

Something like:

``` yml
version: '3'
services:
  api:
    image: registry:3000/api
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
  frontend:
    image: registry:3000/frontend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
```

```
docker run -v .:/workspace gcr.io/kaniko-project/executor:latest --compose ./docker-compose.yml --compose ./docker-compose.override.yml -c /workspace/
```

**Comment by Martaver** [comment]
We're in the same boat. We have a single `docker-compose.yaml` that defines our build and pushes tagged images. It also fires up the stack for local development. Very neat, because there's a single source of truth, and we run the same docker-compose build in GCB. Simple and repeatable.

The only downside is that we can't use the kaniko cache, and there's a lot of wasted resources.

The alternative is to configure each image build individually in cloudbuild.yaml, but then we lose the single source of truth.

**Comment by abdennour** [comment]
what's the plan for docker-compose, podman-compose ? 
We had same reason as @martaver explained about why docker-compose as build strategy : Single source of truth for all : 
- For developers : it's `up -d` and `down`
- For CI/CD : it's `build` and `push`.

We threw out many build strategies alternative (like s2i) for that sake.

**Comment by grugnog** [comment]
One change that may make this perhaps more feasible is making compose an open standard with (non-python based) reference libraries for parsing: https://github.com/compose-spec

**Comment by shibumi** [comment]
Would love to see this feature-request implemented, too

**Comment by morganchristiansson** [comment]
As an example `docker buildx bake` supports docker-compose.yaml in addition to docker-bake.hcl https://docs.docker.com/engine/reference/commandline/buildx_bake/#file

**Comment by abdennour** [comment]
I am gonna contribute to [docker/compose](https://github.com/docker/compose) & add it: 

```yaml
services:
    s1:
       build:
         context: .
         provider: kaniko
.....
```
If you got time before me, please do.
Otherwise, i will as i've already extended it
