### ISSUE TITLE
"GET https://example.com/users/sign_in: unexpected status code 200 OK" when pushing to self-hosted GitLab with Kaniko

### ISSUE THREAD

**Issue by andrew2758** [GoogleContainerTools/kaniko#3146]
**Actual behavior**

When attempting to publish a Kaniko-built image to a self-hosted GitLab server (which I'll call example.com in this issue), we get the following error:

```
$ /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "registry-example.com:443/me/registry-test:v0.0.14": GET https://example.com/users/sign_in: unexpected status code 200 OK: <!DOCTYPE html>
<HTML of the of the user login page>
...
```

The build stage is successful if we provide `--no-push`. It looks like what might be happening here is that as Kaniko tries logging into the registry at registry-example.com/v2/, and it at some point decides to visit example.com. That automatically redirects it to the user login page, which doesn't contain the expected data. (Our GitLab instance requires a login to view the `/` path on that site, but other public groups and repos are visible if you know their URLs).

I looked at the output of the `env` command in our runner, and that shows some entries that contain 'example.com', but it's not clear whether any of those are influencing Kaniko's behavior.

Is Kaniko looking for some data on the main page of our GitLab instance?

**Expected behavior**

The expected behavior is for Kaniko to log into the container registry, so it can push an image to it.

**To Reproduce**
1. Create a self-hosted GitLab server installed via Omnibus.
2. Block anonymous viewing of the base path of the GitLab application.
3. Configure a separate domain to serve the registry API.
4. Use the following CI scripts in a new repo:

**Additional Information**

`gcr.io/kaniko-project/executor:v1.22.0-debug` (likely `c7c1f8d3d464`)

`Dockerfile`:
```
FROM ubuntu:mantic
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git yamllint

CMD /bin/bash
```
`.gitlab-ci.yml`:
```
---
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: ["/bin/sh"]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - echo "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - env
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
```

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
