### ISSUE TITLE
--single-snapshot seems to be ignored

### ISSUE THREAD

**Issue by cdprete** [GoogleContainerTools/kaniko#3215]
Hello.
I've a GitLab job like the following:

```yaml
.docker:
  image:
    name: artifactory.foo.net/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - APP_VERSION=$(cat "$APP_VERSION_FILE")
  script:
    - |
      if [ "$REPOSITORY_TYPE" = "" ]; then 
        /kaniko/executor --no-push --context "$CHART_PATH" --single-snapshot --use-new-run --build-arg APP_VERSION="$APP_VERSION"
      else
        /kaniko/executor --context "$CHART_PATH" --single-snapshot --cache=true --use-new-run --build-arg APP_VERSION="$APP_VERSION" --destination "news-docker-$REPOSITORY_TYPE-local.artifactory.foo.net/opensearchproject/opensearch:$APP_VERSION"
      fi
  rules:
  - exists: [ "$CHART_PATH/Dockerfile" ]
```

and from the output I can see that multiple snapshots are created, even if  `--single-snapshot` is specified:
> $ APP_VERSION=$(cat "$APP_VERSION_FILE")
$ if [ "$REPOSITORY_TYPE" = "" ]; then  # collapsed multi-line command
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch:2.14.0 
INFO[0000] Retrieving image artifactory.foo.net/opensearchproject/opensearch:2.14.0 from registry artifactory.foo.net 
INFO[0000] Built cross stage deps: map[]                
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch:2.14.0 
INFO[0000] Returning cached image manifest              
INFO[0000] Executing 0 build triggers                   
INFO[0000] Building stage 'artifactory.foo.net/opensearchproject/opensearch:2.14.0' [idx: '0', base-idx: '-1'] 
INFO[0000] Unpacking rootfs as cmd RUN chmod -R 777 /usr/share/opensearch requires it. 
INFO[0043] Initializing snapshotter ...                 
**INFO[0043] Taking snapshot of full filesystem...**        
INFO[0045] RUN chmod -R 777 /usr/share/opensearch       
INFO[0045] Cmd: /bin/sh                                 
INFO[0045] Args: [-c chmod -R 777 /usr/share/opensearch] 
INFO[0045] Util.Lookup returned: &{Uid:1000 Gid:1000 Username:root Name: HomeDir:/home/1000} 
INFO[0045] Performing slow lookup of group ids for root 
INFO[0045] Running: [/bin/sh -c chmod -R 777 /usr/share/opensearch] 
**INFO[0046] Taking snapshot of full filesystem...**        
INFO[0072] Skipping push to container registry due to --no-push flag 
Cleaning up project directory and file based variables
00:00
Job succeeded

The Dockerfile is just
```docker
ARG APP_VERSION=2.14.0
FROM artifactory.foo.net/opensearchproject/opensearch:$APP_VERSION

RUN chmod -R 777 /usr/share/opensearch
```
