### ISSUE TITLE
--snapshot-mode seems to be ignored

### ISSUE THREAD

**Issue by cdprete** [GoogleContainerTools/kaniko#3233]
Hello.

I've a GitLab job that builds some Docker images with Kaniko according to a matrix:
```yaml
.docker:
  image:
    name: artifactory.foo.net/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
  - APP_VERSION=$(cat "$APP_VERSION_FILE")
  script:
  - /kaniko/executor --context "$CHART_PATH" --single-snapshot --skip-unused-stages --snapshot-mode=redo --ignore-var-run --cache=true --use-new-run --build-arg APP_VERSION="$APP_VERSION" --destination "news-docker-$REPOSITORY_TYPE-local.artifactory.foo.net/opensearchproject/$DOCKER_IMAGE:$APP_VERSION"
  rules:
  - exists: [ "$CHART_PATH/Dockerfile" ]
```

As you can see, I've `--snapshot-mode=redo` set as option, but from the logs of the job I can instead read:
> $ /kaniko/executor --context "$CHART_PATH" --single-snapshot --skip-unused-stages --snapshot-mode=redo --ignore-var-run --cache=true --use-new-run --build-arg APP_VERSION="$APP_VERSION" --destination "news-docker-$REPOSITORY_TYPE-local.artifactory.foo.net/opensearchproject/$DOCKER_IMAGE:$APP_VERSION"
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 
INFO[0000] Retrieving image artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 from registry artifactory.foo.net 
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 
INFO[0000] Returning cached image manifest              
INFO[0000] Built cross stage deps: map[]                
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 
INFO[0000] Returning cached image manifest              
INFO[0000] Retrieving image manifest artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 
INFO[0000] Returning cached image manifest              
INFO[0000] Executing 0 build triggers                   
INFO[0000] Building stage 'artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0' [idx: '0', base-idx: '-1'] 
INFO[0000] Checking for cached layer news-docker-snapshot-local.artifactory.foo.net/opensearchproject/opensearch-dashboards/cache:82aed3b940c469dc95c5bcaff2eacd9caf34f7137156a52296189a49256aa75f... 
INFO[0000] Using caching version of cmd: RUN chmod -R 777 /usr/share/opensearch-dashboards 
INFO[0000] Skipping unpacking as no commands require it. 
**INFO[0000] Initializing snapshotter ...                 
INFO[0000] Taking snapshot of full filesystem...**        
INFO[0000] RUN chmod -R 777 /usr/share/opensearch-dashboards 
INFO[0000] Found cached layer, extracting to filesystem 
INFO[0098] Pushing image to news-docker-snapshot-local.artifactory.foo.net/opensearchproject/opensearch-dashboards:2.15.0 
INFO[0098] Pushed news-docker-snapshot-local.artifactory.foo.net/opensearchproject/opensearch-dashboards@sha256:285b72cc0edaa7a3a65b[51](https://gitlab.foo.net/six/mdprodel/md/news/cns/opensearch-delivery/-/jobs/3317870#L51)a45848f721043863db748f8f01fd3e1b9d988eb358

which looks to me like the option is being ignored completely.
