### ISSUE TITLE
Kaniko fails to pull from GCR in Gitlab

### ISSUE THREAD

**Issue by jgsuess** [GoogleContainerTools/kaniko#3328]
**Actual behavior**

In gitlab, kaniko obtains the manifest of an image, but fails to obtain the image from GCR.

**Expected behavior**
In gitlab, kaniko obtains the image from GCR.

**To Reproduce**
1. In a Gitlab repository, create the files below.
2. Observe build failure

```yaml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
     - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
```
```Dockerfile
FROM gcr.io/distroless/java17-debian12:nonroot
```

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 

```sh
Using docker image sha256:16b383e1c3b259d59f75a2720a45ccf15b3a716cef44c6a5c521ceb471117168 for gcr.io/kaniko-project/executor:v1.23.2-debug with digest gcr.io/kaniko-project/executor@sha256:c3109d5926a997b100c4343944e06c6b30a6804b2f9abe0994d3de6ef92b028e ...
$ /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
INFO[0000] Using dockerignore file: /builds/australian-e-health-research-centre/digital-health-strengthening-standards-capability/infrastructure/containers/hapi-fhir-jpa-server/.dockerignore 
INFO[0000] Retrieving image manifest gcr.io/distroless/java17-debian12:nonroot 
INFO[0000] Retrieving image gcr.io/distroless/java17-debian12:nonroot from registry gcr.io 
error building image: unable to complete operation after 0 attempts, last error: GET https://gcr.io/v2/token?scope=repository%3Adistroless%2Fjava17-debian12%3Apull&service=gcr.io: UNAUTHORIZED: authentication failed
```

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [] </li></ul>|

**Comment by mzihlmann** [comment]
When running as a gitlab job, kaniko automatically sets authentication for you based on the [predefined variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html):
* `CI_REGISTRY`
* `CI_REGISTRY_USER`
* `CI_REGISTRY_PASSWORD`

If you need different credentials either inside gitlab or with other registries, you must manually set these credentials.

ie:
```yml
build:
  variables:
    DOCKER_CONFIG_JSON: |
      {
          "auths":{
              "$MY_REGISTRY":{
                  "auth":"$MY_AUTH"
              }
          }
      }
  before_script:
    - echo $DOCKER_CONFIG_JSON > /kaniko/.docker/config.json
```

**Comment by jameshartig** [comment]
It looks like the OP is trying to fetch `gcr.io/distroless/java17-debian12:nonroot` which doesn't need authentication.

**Comment by mzihlmann** [comment]
indeed. It actually works in my self-hosted gitlab instance too. It's the public one where I can reproduce that issue. So I don't think it's a problem with kaniko. My guess is that we run into the rate-limit on gcr.io side because we all share the same ip range when we run in gitlab.com. But if that is the case, gcr.io is to blame for a very misleading error message.

https://cloud.google.com/blog/products/containers-kubernetes/mitigating-the-impact-of-new-docker-hub-pull-request-limits

what I can see on giltab.com's runners is that there are two env variables defined out of the box:
* `DOCKER_CONFIG=/kaniko/.docker/`
* `DOCKER_CREDENTIAL_GCR_CONFIG=/kaniko/.config/gcloud/docker_credential_gcr_config.json`

but both point to nowhere.

**Comment by mzihlmann** [comment]
Indeed! Sorry for not reading carefully enough. For me however, this only happens on gitlab.com with runners from gitlab.com (docker). on our self-hosted gitlab + self-hosted runners (k8s) this is not reproducible. So it's not necessarily an issue with kaniko. I experimented a bit around and found this fix:

```yml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    FF_NETWORK_PER_BUILD: false
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
```

[FF_NETWORK_PER_BUILD](https://docs.gitlab.com/runner/executors/docker.html#create-a-network-for-each-job)

but I have not yet understood why.
