### ISSUE TITLE
Variables passed by `--build-arg` could not properly read by `Dockerfile`

### ISSUE THREAD

**Issue by ldt1997** [GoogleContainerTools/kaniko#3412]
Problem:
The variables are successfully printed in the environment stage during the pipeline, confirming that they are correctly passed in. However, when attempting to access these variables within the Dockerfile, they are not recognized.

![Image](https://github.com/user-attachments/assets/39c423a2-1bed-4630-a18c-2f8300222b58)

![Image](https://github.com/user-attachments/assets/b7a044ef-9f10-4666-88b4-5622edb1c7a6)

Expected Behavior:
The variables passed with `--build-arg` should be correctly read and used inside the Dockerfile.

Any tips or config changes to make sure build arguments are passed and accessed correctly in the Dockerfile would be helpful:)

Here's my config:
.gitlab-ci.yml

```
image: alpine:latest

variables:
  VITE_BACKEND_HOST: "test" # Default value for VITE_BACKEND_HOST

stages:
  - env
  - build
  # - test
  - deploy

.default_rules: &default_rules
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feat-ci"
  tags:
    - test  # Only run on runners with this tag

env-job:
  <<: *default_rules
  stage: env
  script:
    - echo "VITE_BACKEND_HOST ${VITE_BACKEND_HOST}"
    - echo "CI_COMMIT_SHORT_SHA ${CI_COMMIT_SHORT_SHA}"

build-job:
  <<: *default_rules
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg VITE_BACKEND_HOST=${VITE_BACKEND_HOST}
      --build-arg VITE_IMAGE_TAG=${CI_COMMIT_SHORT_SHA}
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --custom-platform=linux/amd64
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

deploy-job:
 // TODO

``` 
Dockerfile
```
ARG VITE_BACKEND_HOST
ARG VITE_IMAGE_TAG

FROM --platform=linux/amd64 node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# Set environment variables for the frontend to connect to the backend service
ENV VITE_BACKEND_HOST=${VITE_BACKEND_HOST}
ENV VITE_BACKEND_PORT=5000
ENV VITE_IMAGE_TAG = ${VITE_IMAGE_TAG}

RUN echo "VITE_BACKEND_HOST is $VITE_BACKEND_HOST"
RUN echo "VITE_BACKEND_PORT is $VITE_BACKEND_PORT"
RUN echo "VITE_IMAGE_TAG is $VITE_IMAGE_TAG"

# build app for production with minification
RUN npm run build

# Expose port 80 for the application
EXPOSE 80

# Start the application
CMD ["npm", "run", "serve"]
```
