### ISSUE TITLE
Leave workspace intact on Google Cloud Build

### ISSUE THREAD

**Issue by gsf** [GoogleContainerTools/kaniko#426]
I have a cloudbuild.yaml like so:

```
steps:                        
- name: gcr.io/kaniko-project/executor
  args:
  - --context=/workspace         
  - --destination=gcr.io/$PROJECT_ID/image:$COMMIT_SHA 
  - --cache=true
  - --reproducible
- name: gcr.io/cloud-builders/gcloud                                      
  entrypoint: bash                                                        
  args:                            
  - -ex         
  - test.sh
```

The second step runs a smoke test on the built image. This works when run with a docker build and push. With kaniko, the test.sh file is gone because the workspace has been wiped out. Can kaniko run in a way that will leave files in the workspace intact for the next step?

**Comment by priyawadhwa** [comment]
Hey @gsf , do you have a `/workspace/.dockerignore` file? kaniko will delete files in the context (`/workspace`) if they are specified in the `.dockerignore`, but otherwise it shouldn't remove any files in the build context.

**Comment by gsf** [comment]
That project has a .dockerignore that's required for the build. Looks like I'll need a step to tar up the project and send it to Cloud Storage first, then pull it back down to the build context with kaniko?

**Comment by gsf** [comment]
I tried using a different build context directory but ran into the same error. Here is that cloudbuild.yaml:

```
steps:
- name: busybox
  entrypoint: sh
  args:
  - -c
  - cp -rv /workspace /build/context
  volumes:
  - name: build
    path: /build
- name: gcr.io/kaniko-project/executor
  args:
  - --context=/build/context
  - --destination=gcr.io/$PROJECT_ID/image:$COMMIT_SHA
  - --cache=true
  - --reproducible
  volumes:
  - name: build
    path: /build
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -ex
  - test.sh
```

I realized the files in .dockerignore are removed from the executor working directory, so that is the issue rather than the build context. The following configuration works:

```
steps:                         
- name: gcr.io/kaniko-project/executor
  args:                     
  - --context=/workspace    
  - --destination=gcr.io/$PROJECT_ID/image:$COMMIT_SHA
  - --cache=true           
  - --reproducible         
  dir: /build
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -ex
  - test.sh
```
