### ISSUE TITLE
Multistage build is causing deletion of files from kaniko run environment

### ISSUE THREAD

**Issue by mtsyganov** [GoogleContainerTools/kaniko#450]
**Actual behavior**
Before executor is called in the runtime of kaniko the /root/.docker/config.json file is created to allow kaniko access to private registries. 
When multistage build is executed before the image of next stage is downloaded kaniko make deletes the filesystem. After the deletion of the file system also the /root/.docker/config.json file is deleted. As consequence the image of the third stage cant be downloaded form private registry anymore. In the 2 stage builds, after both stages are processed the resulting image cant be pushed to private registry because of missing credentials. 

This problem affects #407 and was not completely fixed with !192 MR https://github.com/GoogleContainerTools/kaniko/pull/192

**Expected behavior**
Deleting of filesystem is not deleting files from kaniko runtime environment at all.

**To Reproduce**
1. Create dockerfile with 3 stage build and images from private registry
2. Run kaniko  in the container and before executor is called create /root/.docker/config.json file
3. Call executor and wait till the third stage is executed. The third image cant be pulled from private registry

**Additional Information**
Dockerfile: 

FROM $CI_REGISTRY_IMAGE:test2 as pg
FROM $CI_REGISTRY_IMAGE:test1 as go
FROM $CI_REGISTRY_IMAGE:latest

Build with gitlab ci pipeline:
```yaml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
```
