### ISSUE TITLE
Using secrets for Docker build

### ISSUE THREAD

**Issue by mustafaakin** [GoogleContainerTools/kaniko#489]
How are we supposed to be using Docker secrets? The regular docker build command has --secret option https://docs.docker.com/engine/reference/commandline/build/ 

I was thinking of mounting the file, using it in the context with COPY and removing it after the execution as I merge the layers, there won't be a history, so secrets won't be pushed but is that a good idea, or the only idea?

**Comment by priyawadhwa** [comment]
Hey @mustafaakin, if I understand correctly, you don't want the secret to end up in the final image?

Any file that is mounted in won't end up in the final image unless you explicitly `COPY` it into the image.

**Comment by mustafaakin** [comment]
Yes, but how should the kaniko use it, where should I mount it exactly? I do not think mounting it in context would be fine, as it needs COPY to be available in the container? I use the kaniko with dir:// contexts, so consider a context has

```
/context/Dockerfile
/context/code.go
```

Kaniko is invoked as:

```
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    args:
    - --context=/context/
    - --dockerfile=/context/Dockerfile
    - --destination={{account_id}}.dkr.ecr.{{region}}.amazonaws.com/{{repo}}:{{tag}}
```

Where should the secret be mounted?
