### ISSUE TITLE
credentials not working anymore from gitlab CI

### ISSUE THREAD

**Issue by mathroc** [GoogleContainerTools/kaniko#529]
Since 996bec885fe3274d92a53935079f03448c44103a (afaict) pushing to gitlab registry from gitlab CI does not work anymore

I have a gitlab-ci.yaml similar to this:

```yaml

build image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh", "-c"]
  before_script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - build="/kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/config/docker/site/Dockerfile --cache --cache-repo $CI_REGISTRY_IMAGE/cache"
  script:
    - $build --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
```

It works again if I use `gcr.io/kaniko-project/executor@sha256:b3ed3368390c0ab105487c4a35e8fff747519dde7f3f9ae6dc2c58d87aea9016` but not with `gcr.io/kaniko-project/executor@sha256:d8097ad1de40491c89e387f390935ee0a861dec30dbbe1c752293cad736c0615` (I found those here : https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor?gcrImageListsize=30)

which is why I suspect 996bec885fe3274d92a53935079f03448c44103a of breaking this

is something need to be changed on how to use kaniko from gitlab ( I followed their doc so it would need to be updated) or is this a bug?
