### ISSUE TITLE
Using `executor:debug` fails with `ERROR: Job failed (system failure): unable to upgrade connection: container not found ("build")` 

### ISSUE THREAD

**Issue by de1m** [GoogleContainerTools/kaniko#590]
**Actual behavior**
I run a kubernetes runner and I get the error below
```
Running with gitlab-runner 10.3.0 (5cf5e19a)
  on runner-gitlab-runner-856c89dd74-szxpz (00dc1024)
Using Kubernetes namespace: gitlab-managed-apps
Using Kubernetes executor with image gcr.io/kaniko-project/executor@sha256:52cd9aac9c73c217ce4b25bd55640d80f0bcece56b7b4783504a74277602c575 ...
Waiting for pod gitlab-managed-apps/runner-00dc1024-project-210-concurrent-02jrjv to be running, status is Pending
Waiting for pod gitlab-managed-apps/runner-00dc1024-project-210-concurrent-02jrjv to be running, status is Pending
Waiting for pod gitlab-managed-apps/runner-00dc1024-project-210-concurrent-02jrjv to be running, status is Pending
Running on runner-00dc1024-project-210-concurrent-02jrjv via runner-gitlab-runner-856c89dd74-szxpz...
Cloning repository...
Cloning into '/dkr/test-build'...
Checking out b53f3b5f as master...
Skipping Git submodules setup
ERROR: Job failed (system failure): unable to upgrade connection: container not found ("build")
```

And my is .gitlab-ci.yml:
```
image: lachlanevenson/k8s-kubectl

services:
  - lachlanevenson/k8s-kubectl:latest

stages:
- buildk8s
- k8s-run-test

variables:
  CONTAINER_NAME: $CI_PROJECT_NAME

tags:
- k8s-int

test-connection:
  stage: k8s-run-test
  image: lachlanevenson/k8s-kubectl:latest
  script:
  - kubectl version
  - kubectl get secret

build_image_master:
  stage: buildk8s
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - echo $CI_PROJECT_DIR
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$DOCKER_REG_URL\":{\"username\":\"$DOCKER_REG_USER\",\"password\":\"$DOCKER_REG_PASS\"}}}" > /kaniko/.docker/config.json
  - cat /kaniko/.docker/config.json
  - /kaniko/executor -v debug --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_REG_URL/$CI_PROJECT_NAME:latest
```
**Additional Information**
My Dockerfile is very simple(it is an example): 
```
# A basic apache server. To use either add or bind mount content under /var/www
FROM ubuntu:bionic

RUN apt-get update && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
```

From kubernetes log:
