### ISSUE TITLE
Run kaniko with PSP runAsUser rule: MustRunAsNonRoot

### ISSUE THREAD

**Issue by steerben** [GoogleContainerTools/kaniko#601]
**Actual behavior**
I try to use the kaniko container as part of a jenkins build slave pod within Kubernetes.
We have introduced pod security policies within the whole cluster which does not allow to run a pod as root user.
(Therefore we have to ditch DIND builds and tried kaniko instead)

I had the impression that kaniko does neither use elevated privileges, nor root.

Is there another user to use within the image?

PSP excerpt:
```
runAsUser:
  rule: MustRunAsNonRoot
```

The pod cannot start, since Kaniko runs with root on default
```
error: container has runAsNonRoot and image will run as root
```

**To Reproduce**
PSP:
```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```
Rolebinding to deault service account
```yaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: add-admin-on-space
    namespace: test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - kind: ServiceAccount
    name: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: psp-restricted
    namespace: test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: psp-restricted
  subjects:
  - kind: ServiceAccount
    name: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Pod template
```yml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  serviceAccountName: default
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-539ddefcae3fd6b411a95982a830d987f4214251
    imagePullPolicy: Always
    tty: true
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 256Mi
```

```sh
kubectl apply --as=system:serviceaccount:psp-example:fake-user -f kaniko-pod.yml -n test
```

**Additional Information**
```sh
k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
