### ISSUE TITLE
Kaniko pod - Run as root or priviliged mode?

### ISSUE THREAD

**Issue by 2020testuser** [GoogleContainerTools/kaniko#626]
**Actual behavior**
I'm using Kaniko pod that would use the Dockerfile that is passed , do the build and push it to Docker registry.  The Kaniko pod creation fails with a permission denied error.

**Expected behavior**
The kaniko pod creation must be successful and no elevated or root user/access needed to run the kaniko container or the pod.

**To Reproduce**
1. Install kubectl in MAC and configure to use the remote K8 cluster
2. Create a namespace in the remote K8 cluster
3. Use Kubectl command in MAC to create the kaniko  pod. The pod creation fails with permission denied error.

4. Below is the sample_pod yaml file

```
apiVersion: v1
kind: Pod
metadata:
    name: kanikopod
spec:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
        - name: kanikopod
          image: <kaniko image repo in org's private docker trusted registry>:latest
          args:
            - "--verbosity=debug"
            - "--context=/workspace"
            - "--dockerfile=/workspace/Dockerfile"
            - "--destination=<org's private repo/reponame/kanikotest"
            - "--cache=false"
          volumeMounts:
            - name: dockersecret
              mountPath: dockerconfigjson
              readOnly: true
            - name: config-json
              mountPath: /kaniko/.docker/
              readOnly: true
            - name: build-context
              mountPath: /workspace/Dockerfile
              readOnly: true
    restartPolicy: Never
    volumes:
        - name: dockersecret
          secret:
              secretName: dockersecret
        - name: config-json
          configMap:
              name: config-json
        - name: build-context
          configMap:
              name: build-context
```
**Additional Information**
The yaml file is above. 
Thanks in advance!

**Comment by marshallford** [comment]
Are you getting the error: `standard_init_linux.go:207: exec user process caused "permission denied"` ? I've tried a both the latest `debug` tag and the `debug-v0.9.0` with no luck. I've already tried setting the security context of the container to `privileged: true` as well. If you aren't getting the same error in the logs please let me know and I will open a seperate issue.

**Comment by neoeinstein** [comment]
I am also experiencing a similar issue with `exec user process caused "permission denied"`, mine while trying to run the kaniko executor in a GitLab CI Kubernetes runner. I am not using any security context changes, and am running the pod as unprivileged.

**Comment by neoeinstein** [comment]
Adding the `.gitlab-ci.yml` file that I have been using to try to get a build running on Kubernetes.

```
stages:
  - containerize

variables:
  KANIKO_VERSION: "0.9.0"
  DEPLOY_IMAGE: a.registry.hub/some-repo/some-image:latest

base:
  image:
    name: gcr.io/kaniko-project/executor:debug-v$KANIKO_VERSION
    entrypoint: [""]
  stage: containerize
  script:
    - |-
        /kaniko/executor \
          --context $CI_PROJECT_DIR \
          --dockerfile $CI_PROJECT_DIR/Dockerfile \
          --destination $DEPLOY_IMAGE
```

**Comment by neoeinstein** [comment]
Also adding a link to a [blog post][1] about something very similar. Perhaps this has to do with docker version?

  [1]: https://sven.stormbind.net/blog/posts/docker_execute_bits/

**Comment by neoeinstein** [comment]
Also adding a link to a [blog post][1] about something very similar. Perhaps this has to do with docker version?

  [1]: https://sven.stormbind.net/blog/posts/docker_execute_bits/

**Comment by marshallford** [comment]
I ran into this issue when using containerd as the runtime in GKE - I think it is unlikely docker is the issue.

**Comment by csquire** [comment]
I'm also running into permission issues trying to use the debug image in Gitlab CI with a K8s security context.

Security context for the pod is set as:
```
securityContext:
  runAsUser: 65534
  fsGroup: 65534
```

Resulting error seems to be from an attempt to place a Dockerfile into the `/kaniko` directory, which the 65534 user does not have permission to do.
```Error: error resolving dockerfile path: copying dockerfile: open /kaniko/Dockerfile: permission denied```

```
/ $ ls -al
total 64
drwxr-xr-x    1 0        0             4096 Jul 26 15:38 .
drwxr-xr-x    1 0        0             4096 Jul 26 15:38 ..
drwxrwsrwx    3 0        65534         4096 Jul 26 15:38 builds
drwxr-xr-x    2 0        0            12288 Jul 26 15:38 busybox
drwxr-xr-x    5 0        0              360 Jul 26 15:38 dev
drwxr-xr-x    2 0        0             4096 Jul 26 15:38 etc
drwxr-xr-x    1 0        0             4096 Jun 19 18:01 kaniko
dr-xr-xr-x  193 0        0                0 Jul 26 15:38 proc
dr-xr-xr-x   13 0        0                0 Jul 26 15:29 sys
drwxr-xr-x    3 0        0             4096 Jul 26 15:38 var
```

**Comment by tejal29** [comment]
@2020testuser Thank you for filing this. 
Please review our docs on Security.  https://github.com/GoogleContainerTools/kaniko#security
kaniko does run as root within the container and hence you are seeing this error.

**Comment by jeunii** [comment]
I have a GKE cluster running version `1.14.10-gke.27`

My kaniko  container runs as a sidecar container to jnlp (I have a jenkins job building images)
```
  - command:
    - /busybox/cat
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/gcr.json
    image: <MY-REPO>/kaniko/executor:debug-v0.17.1
    imagePullPolicy: Always
    name: kaniko
.
.
.
    securityContext:
      privileged: true
      runAsGroup: 9007
      runAsUser: 0
-  image: <MY-REPO>jenkins-slave:sapjvm8-sapmachine11-debian
    imagePullPolicy: Always
    name: jnlp
    securityContext:
      privileged: true
```

But the kaniko pod fails to run and gives the error
```
kl kaniko-00846 kaniko
standard_init_linux.go:211: exec user process caused "permission denied"
```

The pod uses the `gce.privileged` PSP
```
Annotations:     
                      kubernetes.io/psp: gce.privileged
```

And it allows pretty much everything in my cluster
```
 k get psp gce.privileged
NAME             PRIV   CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
gce.privileged   true   *      RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            *
```

Any idea why it would give me a permission issue ?
