### ISSUE TITLE
Ability to fetch SHA of pushed image

### ISSUE THREAD

**Issue by GijsWeterings** [GoogleContainerTools/kaniko#654]
I'm using Kaniko in a Kubernetes cluster, where we want to fire an Operator-based CD pipeline after the image has built. For internal reasons, we always want to work on the basis of image digests and never tags. This means that we can't be sure of the exact digest given to a pushed image, but for parsing the logs from the container.

A great way to do this is to (have the ability to) hook in the Termination Message API from Kubernetes (see [here for more info](https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/)).

What this would permit are setups like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: default
spec:
  containers:
  - args:
    - --dockerfile=/go/src/Dockerfile
    - --context=/go/src
    - --destination=docker-registry.registry.svc.cluster.local:5000/test/app:1.0
    # Flag that opts in to saving the digest in the kaniko executor
    - --logDigest=/kaniko/digest.txt
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    name: kaniko
    # Set the termination path to the logDigest target to attach to 
    terminationMessagePath: "/kaniko/digest.txt"
    volumeMounts:
    - mountPath: /go/src/Dockerfile
      name: dockerfile
      subPath: Dockerfile
    - mountPath: /go/src/main.go
      name: maingo
      subPath: main.go
...
```

To grab the messages from the terminated pods:
```
kubectl get pod kaniko -o go-template="{{range .status.containerStatuses}}{{.state.terminated.message}}{{end}}"
```

Would you see any value in this? the `terminationMessagePath` is by default set to `/dev/termination-log`, which could be a default for the flag. For non-Kubernetes workloads, the flag can point to a file which can be extracted using mounted volumes for example.

WDYT? If you see this as a viable idea, the only addition needed for Kaniko is a way to write the digest to a file within the container.
