### ISSUE TITLE
Docker context is not set to the value of '--context' or 'dir'

### ISSUE THREAD

**Issue by gavingolden** [GoogleContainerTools/kaniko#666]
**Actual behavior**
* When setting a nested `--context` or `dir` directory that contains the Dockerfile and its dependencies,  Dockerfile file operations (e.g. `COPY`) are not executed from the `--context` or `dir` directory. The Dockerfile is found and run, but the `COPY` operation fails because it looks in `/workspace` rather than `/workspace/myContext/`

**Expected behavior**
Dockerfile context is set to either `/workspace/${dir}` or `/workspace/${--context}` depending on which one is used (do they both have the same effect?)

**To Reproduce**
1. Given the following directory structure where the Dockerfile and related dependencies are in a nested subdirectory
```
cloudbuild.yaml
test/
    Dockerfile
    file.txt
    ...
```
2. Run `gcloud builds submit --config=cloudbuild.yaml ./`

**Additional Information**
cloudbuild.yaml
```yaml
steps:
  - name: 'gcr.io/kaniko-project/executor:debug'
    args:
      - --destination=someDestination
      - -v=debug
      - --no-push
      - --context=test
#    dir: test # or this instead of --context
```
test/Dockerfile
```Dockerfile
FROM alpine:latest
COPY file.txt copied-file.txt
```

Error:
```
Step #1: DEBU[0003] Resolved file.txt to file.txt 
Step #1: DEBU[0003] Resolved copied-file.txt to copied-file.txt 
Step #1: error building image: error building stage: lstat /workspace/file.txt: no such file or directory
```
I would expect this to instead be looking for `/workspace/test/file.txt`

For my actual project, the directory structure is this way because I'm using a gradle plugin to transform a fat jar into a layer-optimized image. `gradle build` dumps a generated Dockerfile and dependencies into `build/`
