### ISSUE TITLE
index.docker.io/v2 TLS handshake timeout.

### ISSUE THREAD

**Issue by Aisuko** [GoogleContainerTools/kaniko#679]
I have some doubt has been cast upon the authenticity of the `index.docker.io/v2`.  The docker hub authorization in docker config was 

```
{
	"auths": {
		"10.116.18.93": {
			"auth": "*****************"
		},
		"https://index.docker.io/v1/": {
			"auth": "****************"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.0-beta3 (darwin)"
	}
}%
```

When I use the command `skaffold dev -p build-kaniko`,  But I sometimes get this error:

```
WARN[0010] Error processing base image (alpine:3.7) for ONBUILD triggers: getting remote config: getting image: Get https://index.docker.io/v2/: net/http: TLS handshake timeout. Dependencies may be incomplete.
```
In my opinion, kaniko should get authorization from `https://index.docker.io/v1/`, not from that.
Is there anything I have not noticed? The skaffold config below:

```
apiVersion: skaffold/v1beta10
kind: Config

build: {}
deploy:
  kubectl:
    manifests:
      - k8s-*.yaml
      - service-*.yaml

profiles:
  - name: build-kaniko
    build:
      artifacts:
      -  image: aisuko/skaffold
         kaniko:
           image: gcr.io/kaniko-project/executor:latest
           buildArgs:
             cache: false
      # insecureRegistries: [""]
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.FOO}}"
      cluster:
        pullSecretName: regcred
        namespace: default
        dockerConfig:
          path: /Users/bowen/.docker/config.json
          secretName: auth2
```
