### ISSUE TITLE
Update ECR example in documentation

### ISSUE THREAD

**Issue by vfiftyfive** [GoogleContainerTools/kaniko#686]
Hi, the ECR example doesn't work as is, because AWS region is required.
AWS region should be added as an environment variable in the example:
for example:
```yaml
 volumeMounts:
      - name: aws-secret
        mountPath: /root/.aws/
      - name: docker-config
        mountPath: /kaniko/.docker/
    env:
      - name: AWS_REGION
        value: us-west-1
```

Nic
