### ISSUE TITLE
Kaniko supporting multiple auths

### ISSUE THREAD

**Issue by webmutation** [GoogleContainerTools/kaniko#687]
**Actual behavior**
Currently using A private pull and a private push registry. So user needs to be logged in to both private registries.
Currently when building i get 
"No matching credentials were found, falling back on anonymous"

**Expected behavior**
What is the proper usage for pulling images from docker hub.

**To Reproduce**
1. create private registry for pull
2. create private registry for push
3. create auth for pushing
4. build image
5. see notification "No matching credentials were found, falling back on anonymous" 3x

does the kaniko debug image perform a docker login under the hood... how should I pass it the information?

**Comment by jubel-han** [comment]
Depending on where you are performing the executor, normally, you will need to mount the docker auth `config.json` under the directory of `/kaniko/.docker/` according to [here](https://github.com/GoogleContainerTools/kaniko/blob/master/deploy/Dockerfile#L40).

**Comment by webmutation** [comment]
It is mounted I even inject the same config file I use locally
cat config.json > /kaniko/.docker/config.json

The problem seems to be that it does not recognize more than one registry at a time... so if you have a pull and a push registry that are different say you want to pull from docker hub and push to your private registry it will not work... at least this has been my experience using Kaniko with a gitlab runner. 

I worked around by pulling from a mirror repository that contained docker hub and my own private registries, so I don;t have a blocking issue, its the behavior from kaniko that does not seem correct to me. It should be able to take all the configuration passed

**Comment by MCyprien** [comment]
I have the same kind of problem, I try to publish my container to the gitlab registry and gcr, individually it work, but not with both of them.

```yaml
Build Docker image:
  stage: build
# Using debug image for gitlab-ci purpose https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.10.0
    entrypoint: [""]
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/my_gcr_creds.json"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json 
    - /kaniko/executor --context $(pwd) --dockerfile ./Dockerfile --destination $GCR_REPO --destination $GITLAB_DOCKER_REPO
```

**Comment by AASanchezA** [comment]
any update on this issue, I need to pull from private registry and need to push to aws

**Comment by raphaelLacerda** [comment]
any status on this feature request?

**Comment by edvald** [comment]
@AASanchezA I'd expect you could mount or otherwise write the `/kaniko/.docker/config.json` JSON file as suggested, and just have two keys under `auths`, one for each registry. Did you try that? I'm working on supporting this in https://github.com/garden-io/garden and until I find out otherwise, I'm going on the assumption you can put multiple auths in that file, same as when you configure docker locally.

**Comment by AASanchezA** [comment]
@edvald at the end i solved running two separate jobs on my gitlab-ci.yml one for registry that i need to push the container image, this is working quit well but the image is been build two times

**Comment by gawi** [comment]
If the goal if to be able to publish to GCR and something else, this is absolutely feasible by providing two auth entries in `config.json`.  You would need to authenticate to GCR using a [JSON key file](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file).

What you can't do is to publish to multiple GCR projects having different credentials because the authentication key is the hostname.  You would have more than one entry under `gcr.io`. It wouldn't work.  As a work-around, you could try to use CNAMEs for `gcr.io` such as `us.gcr.io`.

**Comment by Shanuson** [comment]
@gawi how does the config.json looks like in this case? What would be the content of the auth field for gcr:
```

{
  "auths": {
    "some docker registry url": {
      "auth": "a key"
    },{
    "eu.gcr.io":{
    ?? what should be here ??
    }
  }
}
```

**Comment by gawi** [comment]
```
{
  "auths": {
    "https://asia.gcr.io": {
      "auth": "...key 1...",
      "email": "not@val.id"
    },
    "https://eu.gcr.io": {
      "auth": "...key 2...",
      "email": "not@val.id"
    },
    "https://gcr.io": {
      "auth": "...key 3...",
      "email": "not@val.id"
    },
    "https://us.gcr.io": {
      "auth": "...key 4...",
      "email": "not@val.id"
    }
  }
}
```

And the repositories can then be:

- asia.gcr.io/project1/xyz
- eu.gcr.io/project2/xyz
- gcr.io/project3/xyz
- us.gcr.io/project4/xyz

Each of them can have a different account key. Obviously, this is a hack, it doesn't scale and you are at the mercy of the CNAME entries on the Google side. This is a last resort solution.

**Comment by webmutation** [comment]
As far as I can tell this still does not work. I have two registries I would like to push the same image, if I add multiple auths it fails.

In config.json

`{"auths":
	{"registrya.org":
		{"username":"usera","password":"[MASKED]"}
	},
	{"registryb.com":
		{"username":"userb","password":"[MASKED]"}
	}
}`

It will fail running

`         /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile \
         --build-arg IMAGE_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
         --destination $CIA_REGISTRY/$CI_REGISTRY_IMAGE:mock \
         --destination $CIB_REGISTRY/$CI_REGISTRY_IMAGE:mock
`

> error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "registrya.org/labs:mock": UNAUTHORIZED: access to the requested resource is not authorized

So currently to not do a dual build I am pulling and tagging the image and pushing to the other registry. But this sucks.

**Comment by webmutation** [comment]
As far as I can tell this works. I have two registries I would like to push the same image

In config.json

`{"auths":
	"registrya.org":
		{"username":"usera","password":"[MASKED]"}
	},
	"registryb.com":
		{"username":"userb","password":"[MASKED]"}
	}
    }
}`

`         /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile \
         --build-arg IMAGE_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
         --destination $CIA_REGISTRY/$CI_REGISTRY_IMAGE:mock \
         --destination $CIB_REGISTRY/$CI_REGISTRY_IMAGE:mock
`
This prevents the dual build. I did not test with tokens or other types of registries in this case both CIA and CIB are Nexus registries.

**Comment by seboudry** [comment]
If you want to push to GCR using a JSON key file and also to other registries, you must define `config.json` file with `gcr` credential helper alongside with other `auths` registry credentials.

Example with https://docs.gitlab.com/ee/ci/docker/using_kaniko.html and also GCR:
```yaml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /path/to/key.json
  script:
    - |
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        },
        "credHelpers": {
          "eu.gcr.io": "gcr"
        }
      }
      EOF
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --destination eu.gcr.io/gcp-project/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
```
