### ISSUE TITLE
Kaniko cannot copy hidden directory

### ISSUE THREAD

**Issue by achmudas** [GoogleContainerTools/kaniko#718]
**Actual behavior**

When building docker image Kaniko cannot copy hidden directory: 

```
[36mINFO [0m[0258] RUN mkdir ./backend/.test                    
[36mINFO [0m[0258] cmd: /bin/sh                                 
[36mINFO [0m[0258] args: [-c mkdir ./backend/.test]             
[36mINFO [0m[0258] Taking snapshot of full filesystem...        
[36mINFO [0m[0258] RUN touch ./backend/.test/simplefile.txt     
[36mINFO [0m[0258] cmd: /bin/sh                                 
[36mINFO [0m[0258] args: [-c touch ./backend/.test/simplefile.txt] 
[36mINFO [0m[0258] Taking snapshot of full filesystem...        
[36mINFO [0m[0259] RUN ls -la ./backend/.test/                  
[36mINFO [0m[0259] cmd: /bin/sh                                 
[36mINFO [0m[0259] args: [-c ls -la ./backend/.test/]           
total 8
drwxr-sr-x    2 root     node          4096 Jul 19 13:57 .
drwxr-sr-x    4 root     node          4096 Jul 19 13:57 ..
-rw-r--r--    1 root     node             0 Jul 19 13:57 simplefile.txt
[36mINFO [0m[0259] Taking snapshot of full filesystem...        
[36mINFO [0m[0260] No files were changed, appending empty layer to config. No layer added to image. 
error building image: error building stage: lstat /home/jenkins/workspace/tests/backend/.test: no such file or directory
```

**Expected behavior**
It should see all the content in hidden directory and copy it to destination.

**Additional Information**
 - Dockerfile 
  ```
FROM node:8.11.3-alpine as base

WORKDIR /home/node

RUN mkdir ./backend/.test
RUN touch ./backend/.test/simplefile.txt

RUN ls -la ./backend/.test/

COPY ./backend/.test ./backend
```
 - Jenkins slave Pod
```
kind: Pod
metadata:
  name: kaniko
spec:
  serviceAccountName: jenkins
  automountServiceAccountToken: true
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker/
  - name: node
    image: node:8.15.0-alpine
    tty: true
    command:
    - cat
  - name: kubectl
    image: k8s-kubectl:v1.14.4
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  imagePullSecrets:
    - name: secret
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: secret
          items:
          - key: .dockerconfigjson
            path: config.json
```
--- Jenkinsfile
```
...
stage('Create Docker image') {
      container(name: 'kaniko', shell: '/busybox/sh') {
        withEnv(['PATH+EXTRA=/busybox:/kaniko']) {
          sh '''#!/busybox/sh
            /kaniko/executor -f `pwd`/Dockerfile -c `pwd` --skip-tls-verify --destination=<dest>
          '''
        }
      }
    }   
...
```

 - Kaniko Image (fully qualified with digest)
`gcr.io/kaniko-project/executor@sha256:7cb20b4b9b23f3f5997db20adc97c04889efaf1cd57bc00b87b9da9a1754b69f`
