### ISSUE TITLE
executor in GCB is ignoring working directory setup field

### ISSUE THREAD

**Issue by liiri** [GoogleContainerTools/kaniko#731]
When specifying a build step with `gcr.io/kaniko-project/executor` image, the step working directory configuration is ignored.

1. Create a repository with a Dockerfile and code nested under some `src` dir. i.e:
```
src
  |--Dockerfile
  |--file.txt
|--cloudbuild.yaml
```
2. In the Dockerfile, assert working directory is `src` and reference some files in there. i.e
```
FROM node:10
COPY file.txt /file.txt
```
2. Create a GCB definition in repo root, i.e
```
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build test docker image
  args: ['--destination=gcr.io/$PROJECT_ID/test:$SHORT_SHA', '--cache=true', '--cache-ttl=12h']
  dir: './src'
```
3. Define a trigger and trigger it.

The build fails with error stating it cannot find the files referenced in the Dockerfile.
So the Dockerfile is located, but the run context is still the root directory.

```
Step #0 - "Build test docker image": error building image: error building stage: lstat /workspace/file.txt: no such file or directory
```

There is a simple workaround, by adding the following to the args: `'--context=/workspace/src'`.

In addition, specifying a relative path in context doesn't work, and hardcoding this directory is not optimal.
For `'--context=./src'`:
```
Step #0 - "Build test docker image": error building image: error building stage: lstat src/file.txt: no such file or directory
```
(since src is search for under `/` and not under current wd `/workspace`)
