### ISSUE TITLE
Connection refused for all URLs (TLS and non-TLS), but works perfectly in kaniko debug 

### ISSUE THREAD

**Issue by axsaucedo** [GoogleContainerTools/kaniko#753]
# Summary
Github repo (context) gets cloned without issues + docker images are pulled without issues when ran SSHing into a `kaniko:debug` but does not work otherwise.

# Actual behavior
Kaniko fails to pull context from github. This can be (and was) circumvented by adding an initcontainer as per #121 (where `alpine/git` pulls the git repo and makes it available through a shared volume). However, in the next stage the Kaniko container still fails to pull any images with `connection refused`. This still fails if the `--insecure-pull` flag is added. This is not due to an issue related to credentials in azure (#425) and it is not (at least directly) related to TLS issues (#168 + #200) because I can confirm it works perfectly when running it directly in a `kaniko-project/executor:debug` container. More specifically, if I run a Kaniko:debug container with `tail -f /dev/null` and then connect into it with `kubectl exec -it kanikobuild sh` the command `/kaniko/executor --context git://github.com/user/repo --no-push` works perfectly. 

It's also worth mentioning that if I use the `debug` container, and try to run it with the command `/docker/executor` (instead of `tail -f /dev/null` and then ssh) then it shows the same strange `connection refused` behaviour.

This was tested in an Azure AKS cluster.

# Expected behavior
To see the same behaviour as the one in the kaniko debug executor. 

# To Reproduce
# Run without init container
Below is the config file without init container. This will show a connection refused to the git repo. This works if actually running it with Kaniko:debug container (as per the example below). This also loads a config secret from file containing the auth required for kaniko.
```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kanikobuilder
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /kaniko/executor 
    args:
    - --context 
    - git://github.com/user/repo
    - --no-push
    volumeMounts:
      - name: config
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: config
      secret:
        secretName: config
```

## Run with init container
This is the version that clones the repo and shares it through a volume. This allows for the next step to be reached, but then the docker pull fails with a `connection refused`. The example below is ran with the `debug` container using the `command: /kaniko/executor` to show that it still fails, but it can be replaced with the `latest` kaniko tag and would show the same behaviour.
```
apiVersion: v1
kind: Pod
metadata:
  name: kanikoinit
spec:
  initContainers:
  - name: init-clone-repo
    image: alpine/git
    args:
        - clone
        - --single-branch
        - --
        - https://github.com/user/repo.git
        - /context
    volumeMounts:
    - name: context
      mountPath: /context
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /kaniko/executor 
    args:
    - --dockerfile 
    - core-builder/Dockerfile 
    - --context 
    - /context
    - --no-push
    - --insecure-pull
    volumeMounts:
      - name: context
        mountPath: /context
      - name: config
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: config
      secret:
        secretName: config
    - name: context
      emptyDir: {}
```

## Debug Container
Now for the strangest part, is to reproduce how the exact same commands actually run perfectly in the debug container. The pod below would create a debug container which runs with `tail -f /dev/null`, so it's possible to connect/ssh into the container using `kubectl exec -it kanikodebug sh`. When connected to the Kaniko image, if the same command `/kaniko/executor --context git://github.com/user/repo --no-push` would work as expected without any issues (context will be cloned from repo, and images will be pulled and built without issues).
```
apiVersion: v1
kind: Pod
metadata:
  name: kanikodebug
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - tail
    args:
    - -f
    - /dev/null
```
