### ISSUE TITLE
Errors to build nodejs in aks

### ISSUE THREAD

**Issue by EnriqueRiveiro** [GoogleContainerTools/kaniko#800]
**Actual behavior**
I've been trying to mount an image with a demo on nodejs.
The problem comes when I run the pod in kubernetes, it seems that it is executing the process but there comes a time that throws me this error

npm ERR! path /root/.npm
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir
npm ERR! rofs EROFS: read-only file system, mkdir '/root/.npm'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

**To Reproduce**
```
FROM node:10
WORKDIR /usr/src/app
COPY ./app/package*.json ./
RUN npm i 
COPY ./app/. .
EXPOSE 3000
CMD [ "node", "index.js" ]
```

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
spec:
  initContainers:
  - name: git-clone
    image: alpine
    command: ["sh", "-c"]
    args: 
    - |
      apk add --no-cache git &&
      git clone ------------------------------------------------
 /context
    volumeMounts:
    - name: context
      mountPath: /context
  containers:
  - name: build-image
    image: gcr.io/kaniko-project/executor:debug-v0.11.0
    imagePullPolicy: Always
    args: ["--cache=false",
      "--dockerfile=/context/dockerfile",
      "--context=/context",
      "--destination=enriqueriveiro13/corekube:testkaniko1"]
    volumeMounts:
    - name: context
      mountPath: /context
    - name:  registry-creds
      mountPath: /root/
  restartPolicy: Never
  volumes:
  - name: registry-creds
    projected:
      sources:
      - secret:
          name: docker-secret
          items:
          - key: .dockerconfigjson
            path: .docker/config.json
  - name: context
    emptyDir: {}
```
