### ISSUE TITLE
Docker: unable to push on a some registry when FROM clause contains a private registry different that target one or a proxy url

### ISSUE THREAD

**Issue by antechrestos** [GoogleContainerTools/kaniko#808]
**Actual behavior**

I am currently trying to build and push an image on a openshift registry. The build is made from outside openshift cluster and push in the end to the openshift registry.

**I am able to do it correctly with docker and the docker push is fine.**

However, when I do it with kaniko it end with the following message

`error pushing image: failed to push to destination default-route-openshift-image-registry.apps.us-west-1.starter.openshift-online.com/test-kaniko/test-kaniko:latest: unsupported status code 401`

I though it might be due to credential problem on my side, yet , I also did on laptop the following command

```
$> docker login -u 'builder' -p '<builder service account token>' default-route-openshift-image-registry.apps.us-west-1.starter.openshift-online.com
```

And then mount the image using the option `-v $HOME/.docker/config.json:/kaniko/.docker/config.json:ro`

Yet, I finally end with the `UNAUTHORIZED` status code.

:warning: I also tried to track the `UNAUTHORIZED` status code with wireshark. This late one just sees all the previous `OK`status code. I am tempted to say  that the underlying library does not handle the large auth header as openshift password used is a jwt token but I am not that sure as previous call are successful.

The issue is related to the fact that the `Dockerfile` contains a `FROM` command whose image is a url through a docker proxy.  

**To Reproduce**
Steps to reproduce the behaviour, you can use openshift as I spotted it on it:

1. Create a dockerfile whose base image is on a private different registry that the target one or through a docker proxy.
2. create a project on openshift and an image stream
3. do your `docker login ` with a `builder`token
4. You can do a `docker build & push` to validate your token
5.  Launch kaniko docker image  `docker run --rm --entrypoint "" -it  -v $PWD:/sources -v $HOME/.docker/config.json:/kaniko/.docker/config.json:ro  gcr.io/kaniko-project/executor:debug  sh`
6. Build with kaniko `/kaniko/executor --context "/sources" --dockerfile "/Dockerfile" --destination "default-route-openshift-image-registry.apps.us-west-1.starter.openshift-online.com/test-kaniko/test-kaniko:latest" --verbosity info --skip-tls-verify --skip-tls-verify-pull `

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>No </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>Yes </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>Yes but also without </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>No </li></ul>|

**Comment by ccremer** [comment]
We also experience this. Interestingly enough, we have a GitLab CI pipeline that builds 2 images ("app" and "echo"), both Jobs are very similar as they extend the same base job ".build".

However, the echo image can be built and pushed fined, while the app cannot.
.gitlab-ci.yml:
```yaml

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    TARGET_STAGE: production
    IMAGE_TAG: ${CI_COMMIT_SHA}
    REGISTRY_USER: none
    REGISTRY_PASSWORD: ${KUBE_TOKEN}
  environment:
    name: integration
    url: https://${KUBERNETES_URL}/console/project/${PROJECT_PREFIX}-${PROJECT}-${CI_ENVIRONMENT_NAME}/overview
  before_script:
  - echo '{"auths":{
    "'${IMAGE_REGISTRY}'":{"username":"'${REGISTRY_USER}'","password":"'${REGISTRY_PASSWORD}'"},
    "'${CI_REGISTRY}'":{"username":"'${CI_REGISTRY_USER}'","password":"'${CI_REGISTRY_PASSWORD}'"}}}' >
    /kaniko/.docker/config.json
  script:
  - echo "destination=${IMAGE}:${IMAGE_TAG}, context=${DOCKER_CONTEXT}, dockerfile=${DOCKER_FILE}"
  - sleep 10000000
  - >-
    /kaniko/executor
    --context ${DOCKER_CONTEXT}
    --destination ${IMAGE}:${IMAGE_TAG}
    --target ${TARGET_STAGE}
    --dockerfile ${DOCKER_FILE}
    --build-arg GIT_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}
    --build-arg GIT_COMMIT_SHA=${CI_COMMIT_SHA}
    --build-arg GIT_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
  only:
  - master
  # temporary
  - merge_requests

app:
  extends: .build
  variables:
    IMAGE: ${IMAGE_REGISTRY}/${PROJECT_PREFIX}-${PROJECT}-${CI_ENVIRONMENT_NAME}/${API_IMAGE_NAME}
    DOCKER_FILE: docker/php/Dockerfile
    DOCKER_CONTEXT: ${CI_PROJECT_DIR}

echo:
  extends: .build
  variables:
    IMAGE: ${IMAGE_REGISTRY}/${PROJECT_PREFIX}-${PROJECT}-${CI_ENVIRONMENT_NAME}/${ECHO_IMAGE_NAME}
    DOCKER_FILE: docker/echo/Dockerfile
    DOCKER_CONTEXT: ${CI_PROJECT_DIR}/docker/echo
```
(the sleep is debugging on the CI runner)

The difference between dockerfiles might be noteworthy:
```
$ cat docker/echo/Dockerfile
FROM node:10-alpine as production
...
```
```
$ cat docker/php/Dockerfile
ARG BASE_IMAGE_TAG=master
FROM registry.gitlab.xxx.tld/images/api:${BASE_IMAGE_TAG} as production
...
```
