### ISSUE TITLE
`RUN` fails because of missing /bin/sh. Dockerfile builds properly with Docker

### ISSUE THREAD

**Issue by ikogan** [GoogleContainerTools/kaniko#823]
**Actual behavior**
When running a kaniko build with skaffold, I get the following error:

```
INFO[0084] Adding whiteout for /usr/local/lib/python3.6/site-packages/wheel-0.33.6.dist-info 
INFO[0089] Pushing layer docker.my.private.registry/ais/adobe-user-sync/cache:bd45d75836ab40d726870b6eaa93483b136ac647b7132ee245a261363ba9aa66 to cache now 
INFO[0089] Using files from context: [/kaniko/buildcontext/docker/entrypoint.sh] 
INFO[0089] COPY docker/entrypoint.sh /entrypoint.sh     
INFO[0089] Taking snapshot of files...                  
INFO[0089] RUN chmod +x /entrypoint.sh                  
INFO[0089] cmd: /bin/sh                                 
INFO[0089] args: [-c chmod +x /entrypoint.sh]           
error building image: error building stage: starting command: fork/exec /bin/sh: no such file or directory
```

**Expected behavior**
For the build to complete successfully as it does when building locally with docker.

**To Reproduce**
1. Try to build the included Dockerfile

**Additional Information**
 - Dockerfile 
```docker
FROM python:3.6-stretch AS build

LABEL maintainer="Ilya Kogan <kogan@ohio.edu>"

RUN mkdir /src && apt-get update && apt-get -y dist-upgrade && apt-get -y install \
    libldap2-dev \
    libsasl2-dev \
    libdbus-1-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install j2tmpl

ARG ADOBE_USER_SYNC_VERSION=2.5

RUN git clone https://github.com/adobe-apiplatform/user-sync.py.git /src/user-sync.py && \
    cd /src/user-sync.py&& \
    git checkout v${ADOBE_USER_SYNC_VERSION}

WORKDIR /src/user-sync.py

COPY docker/user-sync-setup-fix.py /src/user-sync.py/setup.py
RUN make pex && \
    mv /src/user-sync.py/dist/user-sync /usr/bin/user-sync && \
    rm -Rf /src && \
    mkdir -p /etc/adobe/user-sync

COPY docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

COPY config /etc/adobe/user-sync

ENTRYPOINT ["/entrypoint.sh"]
```

 - Build Context
   The `docker/user-sync-setup-fix.py` is required to build Adobe's integration successfully, the fixed version is available in [this gist](https://gist.github.com/ikogan/8ab28de13218240f3bd5139bbf2d33b8).
   The entrypoint can just be any script.
   The config directory isn't required for the build either, I have 3 jinja template files in there.

 - skaffold.yaml in case that's useful:
```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: docker.my.private.registry/ais/adobe-user-sync
  #    docker:
  #      dockerfile: docker/Dockerfile
  #local:
  #  push: true
      kaniko:
        cache: {}
        dockerfile: docker/Dockerfile
  cluster:
    dockerConfig:
      secretName: kaniko-secret
deploy:
  kustomize:
    path: ./kubernetes/test
profiles:
  - name: production
    deploy:
      kustomize:
        path: ./kubernetes/production
```

 - Kaniko Image (fully qualified with digest)
`gcr.io/kaniko-project/executor:v0.10.0@sha256:78d44ec4e9cb5545d7f85c1924695c89503ded86a59f92c7ae658afa3cff5400`

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [Yes] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [No] </li></ul>| 
 
Note: The error happens whether or not I use `--cache``.
