### ISSUE TITLE
kaniko doesn't support multi-stage builds push

### ISSUE THREAD

**Issue by lbouquinUniv** [GoogleContainerTools/kaniko#837]
I have problem with  multi-stage build in docker field. we use gitlab-runner to launch kaniko. 
When we use a single staging in docker file kaniko push without problem but with multi-stage we have this error  error pushing image: failed to push to destination my-harbor-registry.fr/testesup/testesup_srv:v0.0.1: unsupported status code 401. 

Docker build: 
```
FROM debian:9 AS maven

RUN apt-get update  \
#&& apt-get -y install openjdk-8-jdk  \
&& apt-get -y install  maven

COPY ./esup-pay/ /home/
WORKDIR /home/
RUN mvn clean package -DoutputDirectory=/home/target
WORKDIR /home/target
RUN  mkdir war
RUN  cp *.war ./war/esup-pay.war



FROM bitnami/minideb-extras-base:stretch-r377
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-9" \
    OS_NAME="linux"

Install required system packages and dependencies
RUN install_packages libc6 libgcc1 zlib1g
RUN . ./libcomponent.sh && component_unpack "java" "1.8.222-1" --checksum 373c9f3d2943b9ff653fc0e7c69b1d54a75807726691a09190648808500b8253
RUN . ./libcomponent.sh && component_unpack "tomcat" "8.0.53-23" --checksum 0d899a5e407872f0cc5d20631eb83ee2efa837280524b4fb0f388f9f0378d476

COPY ./Docker/Files/rootfs /
RUN /postunpack.sh
ENV BITNAMI_APP_NAME="tomcat" \
    BITNAMI_IMAGE_VERSION="8.0.53-debian-9-r406" \
    PATH="/opt/bitnami/java/bin:/opt/bitnami/tomcat/bin:$PATH"

COPY --from=maven /home/target/war/esup-pay.war /app

EXPOSE 8080

USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]`
```
.gitlab-ci 
```
variables:
  DOCKER_REGISTRY: "my-harbor-registry.fr"
  DOCKER_REGISTRY_PROJET: "testesup"
  DOCKER_REGISTRY_IMAGE_SRV: "testesup_srv"
  DOCKER_REGISTRY_IMAGE_DB: "testesup_db"
  DOCKER_BUILD_REF: "v0.0.1"

 Ces variables sont definies dans le projet gitlab
  DOCKER_REGISTRY_USER:
 DOCKER_REGISTRY_PASS:

  KANIKO_VERSION: "debug"

Build App:
  stage: build
  tags:
    - cluster.ktest
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_VERSION
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$ROBOT_TESTESUP_REGISTRY_USER\",\"password\":\"$ROBOT_TESTESUP_REGISTRY_PASS\"}}}" > /root/.docker/config.json
    - executor --skip-tls-verify  --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Docker/Dockerfile_srv --destination $DOCKER_REGISTRY/$DOCKER_REGISTRY_PROJET/$DOCKER_REGISTRY_IMAGE_SRV:$DOCKER_BUILD_REF
    - executor --skip-tls-verify --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Docker/Dockerfile_db --destination $DOCKER_REGISTRY/$DOCKER_REGISTRY_PROJET/$DOCKER_REGISTRY_IMAGE_DB:$DOCKER_BUILD_REF
```

When i build on my machine i can push in this docker registry. 
Any idea to resolve this issue
