### ISSUE TITLE
COPY does not seem to recursively copy contents of files

### ISSUE THREAD

**Issue by poy** [GoogleContainerTools/kaniko#904]
**Actual behavior**
COPY results in the expected directory structure and files, but the files are empty.

**Expected behavior**
When using the `COPY` command on a directory structure that has some depth, I would expect the files and their contents to be copied.

**To Reproduce**
1. Create the following `cloudbuild.yaml`:
```yaml
steps:
- id: 'prepare workspace'
  name: ubuntu
  entrypoint: 'bash'
  args:
  - "-c"
  - |
    set -eux

    mkdir -p /workspace/public/getting-started/install

    echo "some-content" > /workspace/public/getting-started/install/index.html

    cat << EOF > /workspace/Dockerfile
    FROM ubuntu:latest
    COPY public /workspace
    EOF

- name: 'gcr.io/kaniko-project/executor'
  dir: '/workspace'
  args:
  - --destination=gcr.io/${PROJECT_ID}/some-image:latest

- name: gcr.io/${PROJECT_ID}/some-image:latest
  entrypoint: 'bash'
  args:
  - "-c"
  - |
    set -eux

    size=$(ls -al /workspace/public/getting-started/install/index.html | awk '{print $5}')
    if [ ${size} == 0 ]; then
      echo "FAIL: file is empty"
      exit 1
    fi

    echo "SUCCESS: file is not empty"
```
2. Run in cloud build:
```sh
gcloud builds submit . --config=cloudbuild.yaml
```

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|
