### ISSUE TITLE
Try workload identity for authenticating to GKE

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/kaniko#968]
**Actual behavior**
A skaffold kaniko user opened an issue https://github.com/GoogleContainerTools/skaffold/issues/3468 to use Workload identity for authenticating to GKE https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

This bug is to set up workload identity and try out running a kaniko pod without  environment variable `GOOGLE_APPLICATION_CREDENTIALS` in the pod config..

**Expected behavior**

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by rosmo** [comment]
Hey, I've given this a spin and it seems to work (Gitlab runners in GKE using Workload Identity).

**Comment by jlewi** [comment]
@tejal29 I just tried as well using kaniko 0.23.0 running in Tekton and it worked with workload identity. I think you can close this issue.

**Comment by samos123** [comment]
I confirmed workload identity to work with kaniko 1.0.0 and Tekton as well:
build-image-task.yaml
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker-source.path)/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.inputs.docker-source.path)
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v1.0.0
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    env:
    - name: "DOCKER_CONFIG"
      value: "/tekton/home/.docker/"
    command:
      - /kaniko/executor
    args:
      - --dockerfile=$(inputs.params.pathToDockerFile)
      - --destination=$(outputs.resources.builtImage.url)
      - --context=$(inputs.params.pathToContext)
      - --skip-tls-verify
      - --skip-tls-verify-pull
```

And the taskrun.yaml
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-source-task-run
spec:
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: $(resources.inputs.docker-source.path)/examples/microservices/leeroy-web
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: skaffold-git
    outputs:
      - name: builtImage
        resourceRef:
          name: skaffold-image-leeroy-web
```

I was using the default KSA in the namespace that was associated with an GSA that had storage object admin permission.
